### ISSUE TITLE
Suggestion: OpenFaaS should allow to disable functions

### ISSUE THREAD

**Issue by hivp** [openfaas/faas#1050]
OpenFaaS should allow to disable a function. 
There are cases when we need to disable functions and then enable them again. Actually, we have to remove a function and then redeploy it again.

## Expected Behaviour
- Go to OpenFaaS UI
- Select the function you want to disable
- Disable the function
- The function will not respond when you invoke it.
- Invoke any other function not disabled and it will respond

Another case is disable a function by faas-cli.

## Current Behaviour
Disable a function is not implemented in OpenFaaS. 
We may scale the function to 0, but if we enable the option "scale from zero" in the gateway, the function will scale from 0 to 1 when you invoke the function.

## Pros
An easy way to disable a function when you want to have a function offline for a while.

## Cons
Changes needed in OpenFaaS source code.

**Comment by viveksyngh** [comment]
CLI can be used to remove a function `faas-cli remove <function_name>`. Looks for `faas-cli remove` command for more information.

**Comment by hivp** [comment]
Just trying to suggest a command to disable a function, instead of remove.

**Comment by alexellis** [comment]
Hi @hivp,

I asked you to log this request after speaking on Slack. At the moment I am not sure what value this creates for users of OpenFaaS. I am going to add a label of wontfix, but I could be persuaded to change my mind if enough value in creating the feature was made obvious.

For now your best workarounds have been documented here:

* Remove "disabled" functions
Since all functions are created by the CLI or API (and not edited after deployment) you can always re-create the same function version and state by using the CLI.

* Scale used functions to zero and disable scale from zero

* Feature flag in your code

Your third option is to add a feature flag for your code such as an environment variable.

```js
if(!process.env.enabled) {
     context.status(StatusUnavailable);
}
```

**Comment by hivp** [comment]
Hi @ivanayov @alexellis

There are some use cases where I work when it is better to have an enable/disable (or start/stop):

- Some processes need to run only in certain hours from monday to fridays
- When planning the decommissioning, moving apps out of production, it is not desired to remove the services/functions immediately until to make sure that this has no impact on customers
- In some cases this could save money. If you say for example that a "disabled function" will not run any pods in kubernetes and will not use cpu/memory

These can be very specific use cases but I have seen this feature in Azure and it is very useful.

**Comment by alexellis** [comment]
Derek close

**Comment by alexellis** [comment]
@hivp thanks for your suggestion, we'll consider it in the future if it becomes a pressing need.
