### ISSUE TITLE
Document: Flask usage

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#107]
## Expected Behaviour

With Lambda a modified Flask library can be used called Zappa to handle single requests.

CC @jockdarock

## Current Behaviour

This appears to be incompatible, but..

## Possible Solution

A CGI handler works in its place and lets you retain template functionality and views etc.

**Comment by alexellis** [comment]
Initial worked example: https://gist.github.com/alexellis/39807167e93c29c60342df1f05349add

**Comment by alexellis** [comment]
@JockDaRock - pushed some changes into this branch to support viewing the HTML in a browser. https://github.com/alexellis/faas/compare/107_flask?expand=1

**Comment by alexellis** [comment]
Hey @JockDaRock when you're next free do we have enough to add a sample function and basic guide for this?

**Comment by JockDaRock** [comment]
Yes absolutely, let's get this in there and up and running and see about
blogging about it.

**Comment by alexellis** [comment]
Hey @JockDaRock would be great to know if you have anything on this yet.

**Comment by e-beach** [comment]
Hi @alexellis , I'm also wondering as I'm looking to contribute to this project. If @JockDaRock is busy, I'd like to tackle this.

**Comment by alexellis** [comment]
Sounds great. Are you already on the slack community? The gist provided
allows for a single route site with Flask. The plan is to document this
then look at extending the watchdog and Flask proxy to map incoming
requests to other routes also.

**Comment by JockDaRock** [comment]
Hey @e-beach and @alexellis I have been working on this this weekend.  Long weekend for me in the States.

I have something put together but if you want to also take a stab at it as well @e-beach that is fine with me too.  I got caught up doing it on Saturday and then started thinking I wanted to try and go ahead and extend some functionality to work the way I liked ;).

That being said, in it's current form @alexellis is correct it will only work with one route and you would have to add NGINX as a service to rewrite the request from a GET to a POST.

If you don't want to add in NGINX I have a version of the gateway image that allows you to call functions as GET requests as well.  This would be imperative for use if your looking to call the function / flask web page from your browser.  Just use this Docker compose yml ( https://github.com/JockDaRock/faas/blob/GET_Req/jocker-compose.yml )to deploy your stack instead of the one on the master branch at https://github.com/alexellis/faas.  The you can call functions using GET...

Let me know if you have trouble and I can help you resolve most issues. :)

Kind Regards

**Comment by JockDaRock** [comment]
Hey @e-beach,

I need some help getting rid of the status message from the CGI response for the flask app.

could you research this item from flask / werkzeug library to figure out how to remove the status code when the CGI returns the standard output of the flask page?

the following mod I have removes the headers, now we just need to remove the status code.

```python
#!/usr/bin/python
from wsgiref.handlers import CGIHandler
from flask import render_template
from flask import Flask

app = Flask(__name__)


@app.route('/')
def hello(name=None):
    return render_template('hello.html', name=name)


class ProxyFix(object):
    def __init__(self, app):
        self.app = app

    def __call__(self, environ, start_response):
        environ['SERVER_NAME'] = "localhost"
        environ['SERVER_PORT'] = "8080"
        environ['REQUEST_METHOD'] = "GET"
        environ['SCRIPT_NAME'] = ""
        environ['PATH_INFO'] = "/"
        environ['QUERY_STRING'] = ""
        environ['SERVER_PROTOCOL'] = "HTTP/1.1"
        return self.app(environ, start_response)

    
class HeaderRewriterFix(object):

    def __init__(self, app, remove_headers=None, add_headers=None):
        self.app = app
        self.remove_headers = set(x.lower() for x in (remove_headers or ()))
        self.add_headers = list(add_headers or ())

    def __call__(self, environ, start_response):
        def rewriting_start_response(status, headers, exc_info=None):
            new_headers = []
            return start_response(status, new_headers, exc_info)
        return self.app(environ, rewriting_start_response)

if __name__ == '__main__':
    app.wsgi_app = ProxyFix(app.wsgi_app)
    app.wsgi_app = HeaderRewriterFix(app.wsgi_app)
    CGIHandler().run(app)
```

Let me know if you need any help.

Kind Regards

**Comment by JockDaRock** [comment]
also the purpose of this is so it just returns the straight html without any extra content.

**Comment by alexellis** [comment]
Guys you need to use the branch / PR I pushed up for this a couple of weeks ago. Then set the watchdog env `cgi_body` to `true`. It'll then function how you expect.

**Comment by JockDaRock** [comment]
Thank you @alexellis, I had forgotten about you fixing that

**Comment by JockDaRock** [comment]
So I got the cgi_body watchdog env to work.  Although I was pretty sure this was working before I was not able to get query parameters to work with a single route this time.

Tried using cgi_headers as described in the watchdog doc to pass the query parameters to the flask handler... however, I was not able to get the query parameters to show up in the flask handler or function. When I check all of the env variables, I saw a lot of http header information, but the query parameters were not being passed to the function.

Not that this is pertinent to the 1 route documentation, but forward looking on the flask front... additional information I did not see in the http headers that are being passed as env variables, I did not see any route information in the cgi headers.  This will be important for route mapping in the future for multi route flask applications.

**Comment by JockDaRock** [comment]
On a more good news front... testing on a single route, with no query parameters still works well and I tweaked the flask code for the handler to make the flow of the flask developer a bit easier.  This way the dev can drop in a basic flask application, e.g. app.py, and the handler.py will call the app file and app object and use the proxy fix in handler.py the same as before.

This will make it easier from the point of not having to modify the actual flask app code and could theoretically just drop in their app.py code unmodified and the handler will take care of the rest.

**Comment by alexellis** [comment]
You'll need to use the proxy to set the request parameters by reading them from the variables that are set at runtime. 

```
$ docker rm -f show-env; docker run -e cgi_headers=true -e fprocess=env -p 8081:8080 --name show-env -ti functions/alpine

$ curl "localhost:8081/query=string&test=yes" -d "test"

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=a59aedb83de5
TERM=xterm
cgi_headers=true
fprocess=env
no_proxy=*.local, 169.254/16, 127.0.0.1
HOME=/root
Http_User_Agent=curl/7.49.1
Http_Accept=*/*
Http_Content_Length=4
Http_Content_Type=application/x-www-form-urlencoded
Http_Method=POST
```

Query string serialisation might be in this PR rather than main code.. can you check it out?

**Comment by alexellis** [comment]
OK I've fixed a small bug causing the query string not to be passed:

https://github.com/alexellis/faas/commit/b9be8293a84bcdac11e845dc613ab12d6fcd0a90

You need to manually re-build the watchdog.

**Comment by alexellis** [comment]
@JockDaRock see also - https://github.com/alexellis/faas/pull/174/files

**Comment by aafrey** [comment]
would something like this make sense for the concept of microfrontends?

**Comment by JockDaRock** [comment]
this could definitely be used for that @aafrey .

**Comment by JockDaRock** [comment]
I have also made some updates on my fork of this since Alex last updated.

You can view those changes here...

https://github.com/alexellis/faas/compare/cgi_body...JockDaRock:cgi_body?diff=split&name=cgi_body

**Comment by JockDaRock** [comment]
If you want to build it yourself you can try these commands in a [Play-With-Docker instance](http://play-with-docker.com).  This is assuming you don't want to change the flask app though... if you want to change the app you can do that after downloading the repo and doing the git checkout and the issue the remaining commands.

```
$ git clone https://github.com/JockDaRock/faas && \
cd faas && git checkout cgi_body && \
cd watchdog && ./build.sh && cd .. && \
cp watchdog/fwatchdog sample-functions/BaseFunctions/flask/handler/fwatchdog && \
cd sample-functions/BaseFunctions/flask/handler && \
docker build -t flask_faas:latest . && \
cd $HOME/faas/gateway && ./build.sh && cd .. && cd sample-functions/BaseFunctions/flask && \
docker swarm init --advertise-addr eth0 && \
docker stack deploy func -c docker-compose.yml
```

after a couple minutes, you can access the web page directly in your browser.  Below are some samples you can try, just replace the play with docker portions with your instances of play with docker links.  The folder pathes should be the same...

http://pwd10-1-32-4-8080.host4.labs.play-with-docker.com/function/func_flask
http://pwd10-1-32-4-8080.host4.labs.play-with-docker.com/function/func_flask?name=Jock
http://pwd10-1-32-4-8080.host4.labs.play-with-docker.com/function/func_flask?name=Jock&nickname=JockDaRock
http://pwd10-1-32-4-8080.host4.labs.play-with-docker.com/function/func_flask/test
http://pwd10-1-32-4-8080.host4.labs.play-with-docker.com/function/func_flask/test?name=AwesomeSauce

**Comment by JockDaRock** [comment]
@e-beach, @aafrey, @johnmccabe if you want to give the above a try I would like to see what you think.

**Comment by JockDaRock** [comment]
I have also done an implementation of the new flask support with my [Time2Code project](https://github.com/JockDaRock/Time2Code).  I was originally using a separate service to run my in-browser IDE alongside OpenFaaS.  Now the IDE (based in Flask) can be served up as a function.

if you want to try it out press the button ;)

[![Try in PWD](https://cdn.rawgit.com/play-with-docker/stacks/cff22438/assets/images/button.png)](http://play-with-docker.com?stack=https://raw.githubusercontent.com/JockDaRock/Time2Code/faas_cgi_testing/time2code-ide-deploy.yml&stack_name=func)

Once it is up and running, try copying and pasting the following links, but replace **pwd10-1-12-3-8080.host4.labs.play-with-docker.com** before pasting the link in your browser...

**Base Time2Code functionality**
* Base URL: http://pwd10-1-12-3-8080.host4.labs.play-with-docker.com/function/func_time2code
* Lang Change Query: http://pwd10-1-12-3-8080.host4.labs.play-with-docker.com/function/func_time2code?lang=golang
* Included Code from github repo: http://pwd10-1-12-3-8080.host4.labs.play-with-docker.com/function/func_time2code?code=https://github.com/JockDaRock/Time2Code/blob/faas_cgi_testing/code.txt
* Included code from straight text: http://pwd10-1-12-3-8080.host4.labs.play-with-docker.com/function/func_time2code?straight_text=print("Hello World!!!")

**Tutorial Mode Functionality**
* Base URL: http://pwd10-1-12-3-8080.host4.labs.play-with-docker.com/function/func_time2code/tutorial
* GitHub Markdown tutorial: http://pwd10-1-12-3-8080.host4.labs.play-with-docker.com/function/func_time2code/tutorial?tut=https://github.com/JockDaRock/Time2Code/blob/faas_cgi_testing/QuickCodeTutorial.md

**Comment by aafrey** [comment]
@JockDaRock i'll run through this tomorrow! (9/15)

**Comment by e-beach** [comment]
@JockDaRock 
The Flask function works with GET requests, but isn't it supposed to work with POST requests?
The "invoke" button of http://pwd10-0-43-3-8080.host4.labs.play-with-docker.com/ui/ sends a post request to those URLs, so that doesn't work currently.

**Comment by JockDaRock** [comment]
Hey @e-beach, 
Thank you for testing! technically it does work with POST, it is just that Flask be is returning a 405. The function itself is working as far as OpenFaaS is concerned. 

Mission, if you choose to accept it ;), Is modify the main flask route, @app.route('/'), to accept both GET AND POST methods in the app.py file and then redeploy the function. You should get a different result when you execute the function from the OpenFaaS UI. 

Let me know if you have any questions.

**Comment by e-beach** [comment]
@JockDaRock Thanks!  I tested that change at https://github.com/e-beach/faas/commit/7fd943ace843e095fb3a65e965042ef25a81d923 and it behaves correctly.

**Comment by JockDaRock** [comment]
Thank you @e-beach! YOU ROCK!! Your help is greatly appreciated.

If you have any ideas for flask apps we can demo, that would be great! There was a flask blog I was looking to deploy and demo, but either something like that or other applications would be great. Maybe you can pick something out and make it work. Thoughts?

**Comment by e-beach** [comment]
@JockDaRock I could probably do that. One question would be what constitutes a good app - I'm thinking something simple, that most people familiar with Flask will appreciate. It'd be cool to do httpbin.org.

**Comment by JockDaRock** [comment]
@e-beach So I did the httpbin.org app last week and changed and added some code to my fork of the [httpbin repo](https://github.com/JockDaRock/httpbin) under the faas_flask branch. I made some changes to make it work, but this particular app does highlights some interesting things about having flask as a function.

**Redirects basically don't happen.** This is due to the nature of the CGIHandler and how it returns the seen content. If you have any ideas on how to fix that, I am all ears for that.

**Relative routes in HTML don't work.** Relative routes in HTML won't include the appropriate function information of the route. I fixed this in my version of httpbin app by adding some JavaScript to help turn the routes into absolute paths. I also have mixed feelings about this one as relative paths have plagues me many times in my career and my opinion is absolute paths are just a lot easier to deal with when you have to proxy a web page / site.

**Some of the source http information is not being passed to the flask app**. This becomes apparent when you try going to the IP address route of the httpbin app. This would have to be fixed from OpenFaaS and we would have to add logic to pass that information along through the headers. Would need to talk to @alexellis about that.

**Httpbin app is a bit slow on the return.** This might be due to the size of the app. But it definitely is slow on the return. Maybe just needs to have Afterburn / FastFork used with it. @e-beach If you want to try Flask with fast fork that would be cool. I have been meaning to get to that portion but I haven't quite made it there yet.

**Comment by e-beach** [comment]
> Httpbin app is a bit slow on the return. This might be due to the size of the app. But it definitely is slow on the return. Maybe just needs to have Afterburn / FastFork used with it. @e-beach If you want to try Flask with fast fork that would be cool. I have been meaning to get to that portion but I haven't quite made it there yet.

I'll start working on doing a speed comparison of httpbin  with/without Fast Fork.

> Redirects basically don't happen. This is due to the nature of the CGIHandler and how it returns the seen content. If you have any ideas on how to fix that, I am all ears for that.

My impression is that, ideally, complete response information and redirects would be possible.
Amazon has a [blog](https://aws.amazon.com/blogs/compute/redirection-in-a-serverless-api-with-aws-lambda-and-amazon-api-gateway/) on how they implement redirects for Lambda. Something like that would be useful for faas.

**Comment by alexellis** [comment]
We really do not need any speed testing doing on this until the work is completed. I haven't been able to add to help with being away. Can we focus on addressing the remaining issues?

**Comment by e-beach** [comment]
Yes, but the remaining issues are also related to open-faas code.

**Comment by JockDaRock** [comment]
Potentially if you think the core code changes I have made in addition to your changes @alex on the cgi_body branch, are good, I can do a pull request and we can merge the current changes and worry about the other issues in a different branch. Thoughts?

I feel like we have a lot of added enough functionality to make the UX for the flask developer easy enough.  We can always point out in the guide we currently do not support redirects or obtaining source IP information from the user request.  I do think we should add that functionality, to at least match with what Lambda is capable of doing. But we can release  the current changes in the mean time...

**Comment by alexellis** [comment]
The next couple of weeks are going to be tight on time and I need to catch up on the thread to see where we are and what changes were needed in FaaS, the Flask proxy and the watchdog . @e-beach @JockDaRock thanks for helping move this forward

**Comment by aafrey** [comment]
@JockDaRock played with this this weekend. very cool! first time looking at your time2code project too, but that looks great 👍

**Comment by JockDaRock** [comment]
Hey @aafrey Thank you for taking a look at the Flask updates... 

I think once we have Flask usage ready for the Python Flask community to try, it will be a big win for OpenFaaS

if you wanted to take a look at a demo of a more complicated flask application, please use this PWD button... [![Try in PWD](https://cdn.rawgit.com/play-with-docker/stacks/cff22438/assets/images/button.png)](http://play-with-docker.com?stack=https://raw.githubusercontent.com/JockDaRock/Time2Code/faas_cgi_testing/time2code-ide-deploy.yml&stack_name=func).

* Ex. http://pwd10-0-2-3-8080.host4.labs.play-with-docker.com/function/func_httpbin

This is the Flask application that the httpbin.org site uses in production.  The site mostly functions, but due to some of the unsupported features, not all of the routes work exactly like the site. e.g. you won't be able to return the source IP address from where the function is being called and redirects currently don't work.  But it is interesting to see that most of the functionality is there.  which I still think is a big win.

**Comment by mjhea0** [comment]
What's the status of this?

**Comment by alexellis** [comment]
This work has not been continued due to lack of interest from the community.

However - I think it may be easy to support via the new flask template I've been working on with the "HTTP mode" in of-watchdog. https://github.com/alexellis/python27-flask-template
