### ISSUE TITLE
UI Feature: update UI to use new functions.json

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1145]
## Expected Behaviour

The UI (written in Angular 1.x) needs a minor change to start reading functions.json instead of store.json.

See context here: https://github.com/openfaas/store/pull/63

## Current Behaviour

We are using store.json, but functions.json is better since it is a single file containing all the platforms (i.e. ARM or regular PC) for each function.

## Possible Solution

* Update the build script of the UI in this repo so that it embeds an env-var instead of replacing the store filename i.e. now it sets store-armhf.json vs store.json, but needs to always read functions.json
* Update UI code for the store modal dialog so that it renders data from the new structure in functions.json

https://github.com/openfaas/store/blob/master/functions.json

## Steps to Reproduce (for bugs)

1. Open store UI and see only functions built for the platform on which the gateway is running

## Context

#1099

**Comment by zeerorg** [comment]
Derek assign: me

**Comment by zeerorg** [comment]
The dashboard currently has no way of knowing what architecture the server is running on since there is no compilation step for dashboard. 
3 things can be done:
1. The dashboard queries for architecture and then uses that to filter through functions.
2. The dashboard queries for functions from gateway which queries it from the functions.json and returns only the functions filtered by architecture.
3. The user selects which architecture function they need to deploy. 

The 3rd option needs a UI change but doesn't need to know about the architecture. 1st and 2nd option need the architecture from host.

**Comment by alexellis** [comment]
This is not correct.

The architecture works fine already in the UI and this value is hard-coded at build-time into the HTML assets.

https://github.com/openfaas/faas/blob/master/gateway/Dockerfile.armhf#L58

Alex

**Comment by zeerorg** [comment]
Sorry, I definitely wouldn't have caught that. This seems good.
I'll do the UI part next

**Comment by alexellis** [comment]
@zeerorg please could you provide an update?

**Comment by zeerorg** [comment]
This has been completed and merged in PR #1153

**Comment by zeerorg** [comment]
Derek close
