### ISSUE TITLE
Suggestion: multiple queues for asynchronous functions

### ISSUE THREAD

**Issue by daikeren** [openfaas/faas#1177]
## Summary
Currently all async functions using only one topic `faas-request`, if we want to guarantee the level of parallelism for some function (ex. we will have at least 10 workers to process a particular function), we need multiple topic support to achieve this.

## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

* When invoke async function, use `x-queue-topic: faas-request-high` to route this async function into nats with `faas-request-high` topic
* We have multiple deployment with nats-queue-worker with different topic to consume async function

## Current Behaviour

Currently only one topic `faas-request` is supported.

## Possible Solution

1. Get header `x-queue-topic` when async-function is invoked and pusblish to corresponding subject.
2. Make the topic in nats-queue-worker could be configured from environment variable.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by zeerorg** [comment]
I think @LucasRoesler  might be able to take a look at this when he's free. Also more details on your specific use case could be helpful.

You can get more parallelism on your async invocation by deploying more replicas of queue-worker checkout https://docs.openfaas.com/reference/async/#how-it-works

**Comment by daikeren** [comment]
Thanks for your reply.

Since nats does not support priority queue, if we to have some functions to be executed as soon as possible, one way to do this is to have a specific group of nats-queue-worker for this. 

In current design, even we have multiple queue-worker, when all workers are busy, we need to wait until all jobs are consumed.

**Comment by alekar** [comment]
Can we delegate queueing to a queue-provider? Then what queue to pick can be a semantic, or configuration common to the queue-provider and queue-worker.

This also decouples the current gateway from using NATS. People could trivially plugin SQS or Kafka, which are other popular alternatives via configuration.

**Comment by zeerorg** [comment]
Having an ability to plug in a different queue-provider (like kafka instead of nats) could be useful. A proper proposal would certainly help in grasping the requirements.

**Comment by alexellis** [comment]
Hi we're talking about two different use-cases here if I am reading correctly.

1) Users are interested in having multiple topics for asynchronous work

> if we want to guarantee the level of parallelism for some function (ex. we will have at least 10 workers to process a particular function), we need multiple topic support to achieve this.

I'm not sure that this is a correct assumption. To increase parallelism you just need to scale the queue-worker with additional replicas. This can also be driven through HPAv2 in Kubernetes making it a "no-ops" experience

If this is what you want, then please make a clearer case for it, because I haven't understood why this isn't already possible from the current feature-set.

2) Users are interested in different back-ends such as SQS instead of NATS

Tying into an AWS eco-system is a non-goal for OpenFaaS, by default it must be portable to any Kubernetes cluster. There is a streaming video company who do rely on AWS and built their own SQS queue-worker. I'll let them chime in here if they want to talk about it more. Otherwise I suspect that in time we will add some extension points for queueing and de-queuing work and extend this ecosystem.

3) Potential confusion between the asynchronous processing bus and "event triggers"

Please be aware that the NATS Streaming component is only about asynchronous processing, it is not an event source. Any event source can already be added through the use of the OpenFaaS event-connector SDK including: SQS, SNS, Kafka, Redis, Cron, vsphere and many others. (see the docs for more)

**Comment by alexellis** [comment]
@alekar @daikeren please could you respond to my comment from May?

**Comment by alexellis** [comment]
Closing at duplicate of #1330

**Comment by alexellis** [comment]
daikeren please see #1513
