### ISSUE TITLE
Question about context in functions

### ISSUE THREAD

**Issue by menardorama** [openfaas/faas#1206]
Hi,

We are planning to use OpenFaaS for a faas backend on our application.

We wonder how is it possible to have an "isolated" context for each function call ?

Regarding storage for example : memory or disk ?

I don't see anything regarding this in the documentation or previous issues.

Thanks a lot, by the way it's a great product

**Comment by alexellis** [comment]
Hi,

Thank you for your interest in our work. Rather than asking for a specific technical implementation, please could we start this conversation with your use case? Tell me as much as you are able to. No confidential data is required. 

Alex

Btw. OpenFaaS is a project, not a product.

**Comment by menardorama** [comment]
We are building a data lake for science and we are planning to open the application to scientists.

For that we thought that the match would be to provide a FAAS functionality in order to provide access to the stored data (in our data lake).

The whole is hosted on a Kubernetes cluster.

So we use an oauth2 server (internal to the application) and each function call have to be contextualized (ACL, temp files and so on).

So my initial question was regarding the security context when we call the function. We have to ensure that each call would "isolated"  in all aspect.

Thanks great PROJECT :-)

**Comment by alexellis** [comment]
I think what you're asking for by "context" is a brand-new container per invocation. This is not a supported use-case for the project.

If you'd like to have a completely isolated environment for your scientists, then I would suggest that you deploy one function per scientist.

Alternatively, take a look at OpenFaaS Cloud - https://docs.openfaas.com/openfaas-cloud/intro/

Here's an additional question for you (I'll close the question, because I think it's been answered now) - how would you approach this if you were using a "standard" micro-service?

Alex

**Comment by menardorama** [comment]
I honestly don't know, I'm an Ops....

That question came initialy from our devs

But thanks for the quick feedback

**Comment by alexellis** [comment]
It would be great to hear from your developers. Do they have a spec or compliance statement we can use to understand the usecase more? One thing added recently was concurrency limiting. Perhaps we can limit to 1?
