### ISSUE TITLE
 invocationCount is always 0

### ISSUE THREAD

**Issue by strahe** [openfaas/faas#1243]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

When I get the function information through `/system/function/{functionName}`, `invocationCount` is always 0.
But when I get the function information through `/system/functions`, I can get the correct value.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.13.7
* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
Hi just to let you know that this is as designed

The invocation count is available through the list API. 

Alex

**Comment by alexellis** [comment]
I would recommend retrieving your metrics from Prometheus, especially if you are querying a lot of data.

We may update the rest API so that it outputs null instead of zero

**Comment by nlochschmidt** [comment]
@alexellis just FYI, I tripped over this as well. Not that I want to get the invocationCount through the gateway API, but I was testing the scaling to zero and some other things after an upgrade of openfaas in our cluster and I thought the invocationCount is no longer working, because I was looking only at the responses from `/system/function/{functionName}` 🙈. 

I really wonder though, why the detailed view of a function actually should have less information than the list API in your opinion. I mean, typically  index endpoints have the same or less details than the specific endpoints.
