### ISSUE TITLE
Implement official OpenFaaS training course on Katacoda platform

### ISSUE THREAD

**Issue by kameshchauhan** [openfaas/faas#1270]
There is no official OpenFaaS training course available on Katacoda, which will allow developers to do hands-on training and learning of OpenFaaS function development. 

## My actions before raising this issue
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour
A full training course describing different scenarios should be created on famous Katacoda platform.

## Current Behaviour
Currently there is no training course available providing hands-on experience.

## Possible Solution
Create github repo. following Katacoda training course structure.

**Comment by alexellis** [comment]
Hi @kameshchauhan 

Thank you for creating learning content for OpenFaaS.

It would be great if you could submit a PR to the community.md file in the faas repo, so that we can track your content and promote it.

As for official content, I will put it on my list to take a look through your labs before deciding whether it should be branded that way, or as community content.

The official training labs are the workshop: https://github.com/openfaas/workshop/

@javajon has a katacoda course for OpenFaaS too, maybe the two of you could chat and compare notes? Do you think there are enough differences for two courses, or should they be merged?

Alex

**Comment by javajon** [comment]
Thanks Alex.

I just present it 30 minutes ago to a large group of attendies. Everything
went very smooth. The NoFluffJustStuff tour is currently in Des Moines
Iowa. Nfjs.com

Why have one "official" one? Have many learning mediums to point out the
boatload of great and evolving features.
