### ISSUE TITLE
UI should show that deployment is in progress from store

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1451]
## Description

This relates specifically to the faasd and faas-lambda providers which block and download content when a function or image is deployed.

The UI stays open and remains unresponsive for > 7 seconds (HCI shows that at this point, users assume it's broken). It isn't actually broken, the image is being downloaded synchronously unlike Swarm/K8s where we do it in the background.

The UI should show that deployment is in progress - either with a cursor animation or some other status / info on the screen like going gray and saying "Deployment in progress".

It's quick to reproduce using any large image and the faasd provider - https://github.com/openfaas/faasd

<img width="721" alt="Screenshot 2020-02-22 at 18 47 49" src="https://user-images.githubusercontent.com/6358735/75097583-3925d680-55a4-11ea-8cf6-6741e6cd991a.png">

**Comment by alexellis** [comment]
I think a mouse animation is the minimum we want here, but I am happy to take a quick PR up front to help new users understand that things are "OK" and a more thorough PR after if that's easier for the community.

**Comment by alexellis** [comment]
Example: http://jsfiddle.net/pmrotule/qg9hkm4b/

Note this appears to _not_ work in our version of angular:

```js
$("body").css("cursor", "progress");
```

**Comment by alexellis** [comment]
This is an example of what would be acceptable, as a minimum. But see my note about that `css` feature not working. 

<img width="1336" alt="Screenshot 2020-03-05 at 15 45 10" src="https://user-images.githubusercontent.com/6358735/75998173-53db4200-5ef8-11ea-818b-67558994081a.png">

**Comment by Jeff-Lowrey** [comment]
Very simple thought, probably too stupid and already tested... does $document.find("body").css("cursor", "progress"); work where $body doesn't?

(I know they're equivalent code, but who knows, there might be an oddity somewhere).

**Comment by burtonr** [comment]
Just wanted to mention that I am working on this as I'm able to. 

I've found that the following line *does* show the loading cursor, but for whatever reason, the loading cursor doesn't turn back to a pointer... I'll be going in to it a bit deeper tomorrow evening. Shouldn't take long. Easy 2 line update.

```js
document.body.style.cursor='wait';
```

**Comment by burtonr** [comment]
I've been at this for several hours and cannot get this to work as expected.
Both variations of the css `cursor` do work, however, the style is overridden by the buttons of each function for the store. 

With the css change in place, if the mouse moves to one of the small areas surrounding the button list, the cursor does change to the loading style. 

I've been trying to get the style to override the button styling, which sets the style to `pointer`. It's proving difficult as those elements are generated by Angular when the page is rendered, and the style is very specific, so it takes a higher priority in the css decision.

I'm thinking that this loading indicator should instead be a different element that appears while the request is processing, rather than updating the style on the cursor. This way, we would be able to have more control over it. The downside is that if the request is very fast, there may be a "flash" of the loading element appearing, then disappearing quickly which could cause some confusion.

Something like this (but with a little bit more style of course...)
![Screenshot from 2020-03-15 11-47-04](https://user-images.githubusercontent.com/12687192/76706062-c8f60680-66b2-11ea-8e85-aa15fd78ba9e.png)

**Comment by alexellis** [comment]
I'm not sure that `Loading...` is the correct message for a blocking deployment call.

What about changing the main div so that it says:

"Deployment in progress"

?

https://www.appcues.com/blog/loading-pages-design

https://uxdesign.cc/when-to-use-loaders-empty-states-ebd23cecc7d6

https://uxplanet.org/10-creative-loading-indicators-1a15c562b75a

First three things I found on Google, all seem to have some good ideas. 

Would you like to propose something @burtonr ?

**Comment by mam1101** [comment]
To address @burtonr point on the loading indication "flashing" on quick loads, perhaps including a timer that waits n seconds for a response, then displaying the loading indicator. Though, on the same token, I don't know if flashing a loading indicator is an issue. We could always throw a div overtop with an alpha layered gray background and a centered "Deployment in Progress" to indicate to the user that they cannot interact with the UI at that time.

**Comment by alexellis** [comment]
I'm going to close this since it's not been worked on for two years.
