### ISSUE TITLE
Minimum requirements

### ISSUE THREAD

**Issue by Fillo22** [openfaas/faas#1639]
Where can I find some docs about minimum requirements for installing OpenFaaS on Openshift (or Kubernetes)?

Thx

**Comment by alexellis** [comment]
Hi, given that you need deleted the issue template, where we ask for the context required to help you, it's made answering this question very difficult.

Please feel free to browse the documentation or try it out and measure yourself.

See also: the guides on production and performance testing.

**Comment by Fillo22** [comment]
Hi @alexellis , sorry but when creating the issue from the Github mobile app, no template was available. In any case, thanks for the quick reply, I will search the documentation in more depth.

**Comment by alexellis** [comment]
Is it fair to assume that the question about OpenShift relates to your work/job?

The easiest thing for you to do, would be to read the documentation and just try it out. I can't tell you how many resources it needs because I don't know your use-case or requirements.

It runs on a Raspberry Pi with 1GB of RAM and 4 slow cores. Does that help give you an idea of what's needed? I.e. not very much.

Now, if you are running 10,000 CPU and memory-bound functions, that is obviously going to change.
