### ISSUE TITLE
Question: How do I get the status of an asynchronous invocation?

### ISSUE THREAD

**Issue by junjie-landing** [openfaas/faas#1661]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Expected Behaviour

Scenario: I would like kick off an async function for some moderate job, and come check to view the execution status of the function (whether it is still in-progress, failed or succeeded). 

However I couldn't find any clue to access it. I tried to search every where, including [the docs](https://docs.openfaas.com/), the swagger API, nothing.

To give an example, this is what Openwhisk offer for long running job: http://jamesthom.as/2019/05/accessing-long-running-apache-openwhisk-actions-results/

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by alexellis** [comment]
/set title: Question: How do I get the status of an asynchronous invocation?

**Comment by alexellis** [comment]
Hi yes, please see the [asynchronous documentation](https://docs.openfaas.com/reference/async/#asynchronous-functions) and read up on how callbacks work, and what headers/IDs are sent.

For future reference, GitHub is where we deal with reproducible issues - rather than questions and technical support.

You may benefit from buying the eBook on OpenFaaS, it also covers this topic in detail.

https://openfaas.gumroad.com/l/serverless-for-everyone-else

The documentation also covers other community forums where questions can be asked.

Alex
