### ISSUE TITLE
Stopping many openfaas jobs

### ISSUE THREAD

**Issue by hagna** [openfaas/faas#1677]
## My actions before raising this issue
My use case is stopping a batch after it has started. https://github.com/openfaas/faas/issues/657 seems related because of "batches" and "workflow", but not "long running".

So far the idea for stopping a batch is to do the following:
1. Stop submitting new jobs.
2. Scale queue-workers to 0.
3. Drain nats queue

But I didn't find supporting documentation for this, and thought I'd file an issue before further testing.

## Expected Behaviour

This workflow seems common enough, but maybe it isn't for some good reason. It would be nice to document the reaon. Also, If nats really is buffering when the queue-workers are 0 there ought to be a way of also dropping all queued items instead of needing another service to drain nats.

## Current Behaviour

Scaling queue-workers to 0 does seem to stop the batch of jobs, but it is unclear that step 3 is needed.  If scaling back up does not continue the batch of jobs, then why not?

## Are you a GitHub Sponsor (Yes/No?)

Using openfaas and filing bugs with related software. Happy to contribute PR if this isn't already solved some other way.

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [ x ] No

## List All Possible Solutions and Workarounds

Maybe there is a way for all jobs to gracefully timeout. Maybe instead of scaling queue-workers to 0 the openfaas-fn worker could scale to 0.

## Which Solution Do You Recommend?

Maybe nats could have a timeout for holding on to things or a command to drop all things or maybe a way to observe timeouts have happened?

## Steps to Reproduce (for bugs)

1. Submit N jobs
2. Scale queue workers to 0 before N jobs have finished
3. Scale queue workers back up from 0 after waiting some time.
4. Try to discover what happened.

## Context

I'm trying to stop a batch of jobs.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
 0.13.13
* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.5
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
OpenFaas on Kubernetes
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux ubuntu 20.04 and 18.04

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by kevin-lindsay-1** [comment]
Why are you trying to stop a batch of jobs?

If you want to cancel synchronous invocations, that's easy, just cancel. But async is specifically designed as "fire-and-forget"; why would you create the batch and then cancel it later if your intent is to "fire-and-forget"?

I have an idea or two in mind to your application in such a way that you can do this, but it would use OpenFaaS rather than change it, so purely application logic.

I recommend an application-level logical check, because NATS supports the [concept of a NACK](https://docs.nats.io/nats-concepts/acks), but it would probably be very difficult to get the specific instance of a queue worker to NACK on a specific request, because at that point the queue worker would have to basically subscribe to a "cancel" signal somehow, which would be non-trivial and also probably use a lot more resources than would normally be useful.

Might be easier to have your application understand that it's in a "batch" and check if that batch is cancelled before doing work, but again, I'm not sure why you'd want to cancel it, unless there's a performance reason for it, in which case I'd probably identify the bottleneck and create an issue for that instead.

**Comment by alexellis** [comment]
@hagna we are looking for the Why? Here.

What's making you do this? What usecase do you have, what problem does stopping every asynchronous function solve in your business?
