### ISSUE TITLE
[feature] add custom labels to existing metrics via configuration

### ISSUE THREAD

**Issue by adaliszk** [openfaas/faas#1696]
Great project!
The metrics are covering a lot of angles to display detailed monitoring pages, I'm having a blast putting together dashboards.

I would like to request a possibility to add labels from the functions metadata so that more drill-down analytics could be made without doing cross-references from multiple sources. To avoid bloating the Prometheus, the Network - and to keep a sanity check on this - I think having a variable with a list of labels that should be filled out if present would be good enough.

Have been fiddling around in the code, and it looks to me it could be possible, but I am a bit beginner in Go to see the architecture. What I've found is that adding labels is not too deep. The blocker I run into was that in the handler the metadata - the whole service class - is not there already. The available name there could be used for a getter I suppose, I just have no idea where to look for such a registry.

How does it sound?
Are there any major concerns outside of the possibility that some users may bloat their environment to congestion collapse?

**Comment by alexellis** [comment]
Hi @adaliszk 

We need you to fill out the whole issue template so that we get the kind of information we need as maintainers to support you.

Feel free to edit the issue and ping me to re-open it at that time: https://raw.githubusercontent.com/openfaas/faas/master/.github/ISSUE_TEMPLATE.md

We also have a weekly call that you can attend, to speak to the community about your use-case.

OpenFaaS Pro has more metrics than the Community Edition that you're using now, also happy for you to reach out for a demo or to talk more about it.

https://docs.openfaas.com/openfaas-pro/introduction/

Alex

**Comment by adaliszk** [comment]
Sorry, but I am not interested if you want to push your business on top of open source.
