### ISSUE TITLE
What execution guarantees does OpenFaas give in case of a failure?

### ISSUE THREAD

**Issue by DonRichie** [openfaas/faas#1703]
## My actions before raising this issue
- [ ] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Question
I am currently trying to find out what guarantees are given by OpenFaas when a random failure happens in the system.
For example lets say the function container is gone because the underlying node crashed.
Or the faas-provider failed to reach the watchdog.

Can we maybe summarize this in one of the following terms:
* **At-Least One Execution**
  * invocations are retried and function programmer needs to make idempotent functions to compensate that
* **At-Most One Execution (like in OpenWhisk)**
  * result or failure comes back, no implicit parallel executions and no reexecutions, no idempotence needed
  * client programmer needs to handle failures
* **Exactly One Execution**
  * Each request has an ID and is guaranteed to be executed exactly once

I found the retry mechanism, but it seems to only react on successful http responses which have error response codes.
Thats not what I meant.

Is there maybe a circuit-breaker-pattern implemented? I mean a timeout if the function doesn't come back in a specific period of time?
That would be an indication that OpenFaas is doing At-Most-Once.

## Are you a GitHub Sponsor (Yes/No?)
No

Check at: https://github.com/sponsors/openfaas
- [x] Yes

## Which Solution Do You Recommend?
Friendly answer of my polite question.

**Comment by kevin-lindsay-1** [comment]
Intent is exactly once.

Generally you'd find 1 execution or less. If there's a failure somewhere you should expect an error.
If there's an error and it's not coming from your function, I would raise an issue.

**Comment by alexellis** [comment]
To add to what Kevin said, OpenFaaS Pro supports retrying messages where your function fails to process the payload for a given set of HTTP codes: https://docs.openfaas.com/openfaas-pro/retries/

Feel free to join us on the weekly community call if you want some kind of free, community support.

Otherwise, we have the docs and the code open on GitHub

https://github.com/openfaas

https://docs.openfaas.com

You can also spend some time studying the asynchronous invocation mechanism with [Serverless For Everyone Else](https://openfaas.gumroad.com/l/serverless-for-everyone-else) to understand how call IDs and async works. You'll also find some less detailed info in the docs.

And finally, don't hesitate to contact us about paid support via https://openfaas.com/support/

Alex
