### ISSUE TITLE
HTTP requests sent to Pod before there's an endpoint, with Istio

### ISSUE THREAD

**Issue by kevin-lindsay-1** [openfaas/faas#1721]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

## Why do you need this?

Synchronously invoking functions while using istio.

## Expected Behaviour

With `directFunctions: true`, during a scale-from-zero the gateway intermittently fails to forward the HTTP request to said function scaling from zero.

Here is a table of observed behavior with direct functions on and off, with and without Istio.

| directFunctions? | istio? | error count | attempt count | notes                                         |
|:----------------:|:------:|:-----------:|:-------------:|-----------------------------------------------|
|                  |        |      0      |       10      |                                               |
|                  |    x   |      0      |       10      |                                               |
|         x        |        |      3      |       10      | `status code: 502, body: `                    |
|         x        |    x   |      8      |       10      | `status code: 503, body: no healthy upstream` |

## Current Behaviour

Direct functions are intermittently failing.

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [x] Yes
- [ ] No

## List All Possible Solutions and Workarounds

Based on my previous conversation with @alexellis, it sounds like direct functions uses replica count to determine service availability, whereas without direct functions, it uses endpoint count to determine service availability.

Replica count does not mean the service is available, so that sounds like a quick fix.

## Steps to Reproduce (for bugs)

1. directFunctions: true
2. make sure scale of fn is 0
3. make synchronous request
4. observe elevated error rate
5. repeat for more precise stats for your particular machine

## Context
 

This is affecting invocation on our production functions for synchronous use cases.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  b1c09c0243f69990b6c81a17d7337f0fd23e7542
 version: 0.14.2

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.21.4
 sha:     4e868f5f9d81485740e7951e52e4026a09775a3d


Provider
 name:          openfaas-operator
 orchestration: kubernetes
 version:       0.1.3 
 sha:           8d2c5ab1360721ebcbe49c278929f4a3a1290513
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.14
* Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
k8s
* Operating System and version (e.g. Linux, Windows, MacOS):
multiple
* Code example or link to GitHub repo or gist to reproduce problem:

* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)
The gateway does not appear to log this.

**Comment by alexellis** [comment]
Thanks for logging the issue.

As discussed offline, I have a pretty good idea how to fix this. Let's see if other people run into the same issue now that it's logged and more visible.

As you mention in your testing grid, we do not see the same issue with direct_functions=false, i.e. the option to use without service meshes. I believe this is because the proxy being used load balances between ready endpoints.

In direct_functions=true, the gateway only looks for the deployment to have a ready replica, but doesn't take into account any separate endpoints on the corresponding service.

I'd suggest updating the Virtual Service for the gateway to include a retry (which will lean on Envoy to do the actual work)

https://istiobyexample.dev/retry/

So that someone else, who's not as close to this as you can reproduce the problem, can you provide exact steps including using a function (perhaps from the store?) that reproduces the error?

I.e.

```
kind create cluster
arkade install istio
arkade install openfaas --set operator.create=true --set directFunctions=true
faas-cli store deploy FN
kubectl scale deploy/FN -n openfaas-fn --replicas=0

curl -i http://127.0.0.1:8080/function/FN
```

Something close to that?

**Comment by kevin-lindsay-1** [comment]
You changed the title to "with istio", but this isn't exclusively with istio. Direct functions just uses k8s instead of OF-internal load balancing, correct? I can imagine that some people would actually prefer using k8s' services rather than the gateway picking an endpoint, if that's the difference.

> As discussed offline, I have a pretty good idea how to fix this. Let's see if other people run into the same issue now that it's logged and more visible.

Didn't that already [happen](https://github.com/openfaas/faas-netes/issues/589)? Looks to me like this issue was originally brought up >2 years ago.

Not only that, but other people already confirmed that they were having this same issue on that thread.

> So that someone else, who's not as close to this as you can reproduce the problem, can you provide exact steps including using a function (perhaps from the store?) that reproduces the error?

That looks like it should work. Any function should work, because it doesn't actually invoke the function. This is one of the harder things to give exact replication steps, due to the sheer amount of options available in Istio and OF's helm charts. I'd say give it a try and see what your error rate is.

**Comment by alexellis** [comment]
> I can imagine that some people would actually prefer using k8s' services rather than the gateway picking an endpoint, if that's the difference

That would be a poor choice because K8s is very sticky and in practice it does not load-balance. That's why load-balancing in faas-netes exists

> Istio in thet title

For discoverability, and the issue you're facing needs to work and be tested specifically with Istio for you to be satisfied. It may work generically, but I want us to solve this _for you_ first.

> That looks like it should work. Any function should work, because it doesn't actually invoke the function. This is one of the harder things to give exact replication steps, due to the sheer amount of options available in Istio and OF's helm charts.

I've almost done all the work for you in the previous comment for setting up Istio and OpenFaaS without direct functions. If you'd like us to find someone to help here, it would be appreciated if you spent a little time on it too.

Perhaps run the steps above, and deploy the `sleep` function from the store, which is written in Go? For a repro, it's essential that we don't introduce variables like different languages or watchdog versions.

**Comment by kevin-lindsay-1** [comment]
@welteki thank you, Han. Now that I know it's not as obvious as "turn this option on and watch things break more", I'll see if I can pinpoint a setup and try to narrow down where I think the problem may be.

**Comment by kevin-lindsay-1** [comment]
I looked at this further. @welteki it looks like you used `directFunctions=true`, but it appears that it should be `gateway.directFunctions=true`.

Here are my repro steps:

term 1:
```
kind delete cluster; kind create cluster
kubectl create ns openfaas
kubectl label ns openfaas istio-injection=enabled
kubectl create ns openfaas-fn
kubectl label ns openfaas-fn istio-injection=enabled
helm repo remove istio; arkade install istio
helm repo remove openfaas; arkade install openfaas --set operator.create=true --set=gateway.directFunctions=true
kubectl port-forward -n openfaas service/gateway 8080:8080
```

term 2:
```
PASSWORD=$(kubectl get secret -n openfaas basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode; echo)
echo -n $PASSWORD | faas-cli login --username admin --password-stdin
faas store deploy sleep
kubectl scale --replicas=0 -n openfaas-fn deployment/sleep
```

from here, you can just invoke the sleep function and scale to 0 in a loop, like in Han's tests.

**Comment by welteki** [comment]
> I looked at this further. @welteki it looks like you used `directFunctions=true`, but it appears that it should be `gateway.directFunctions=true`.
> 

I did use `gateway.directFunctions=true` when I tried to reproduce this. However to be sure I retried it using your instructions.

With Istio I'm able to reproduce this and I see the same error rate as mentioned in the table.

Without Istio I don't see the error rate you mention. All invocations are successful.

**Comment by alexellis** [comment]
This issue may be related: https://github.com/istio/istio/issues/14336

@welteki @kevin-lindsay-1 what kinds of issues did you find in the Istio issue tracker or on blog posts / StackOverflow that may suggest a valid workaround?

I'm not sure how busy @howardjohn is. It seems like even, with my patch that only routes traffic when there is an active service endpoint, Istio can still fail to deliver a request.

Is there a separate readiness in Istio that we'd need to query via Istio's own clientset? Or can this be deferred to the network without tight coupling?

**Comment by kevin-lindsay-1** [comment]
What does the gateway see when it's making this request with Istio? Is the 503 coming from the service endpoint directly, the Istio sidecar, or a case post-request in the gateway, before being delivered to the client?

**Comment by kevin-lindsay-1** [comment]
@howardjohn :wave:
> My understanding is directFunctions means there is some faas gateway with a sidecar injected, which sends requests to Pod IPs (from Endpoints object) directly. Is that accurate?

IIRC `directFunctions` means more "k8s native". When it's off (default) the OF gateway looks at the list of service endpoints/pods and routes/load balances internally, whereas with it turned on it uses the k8s environment's method via hitting the k8s service.

> If so, Istio only actually supports this scenario in a few cases which don't seem to be the case here. I would expect Istio to actually load balance across the service even though the pod IP is used since IP is not used for HTTP routing (we are actually working on changing this, but not soon).

I think that would be correct if `directFunctions` were `false`. Maybe it needs a rename to align with the idea of "k8s native".

> And the issue reported is that scale from 0->1 doesn't succeed immediately? That would also seem expected (even without Istio!), since any CNI (kube-proxy, cilium, Istio, etc) has some propagation delay from Endpoints ready to actually serving. I don't think many/any expose additional mechanism to query for readiness there.

Yeah I figured that there'd be a delay, however I'd think that somewhere in k8s there'd be a piece of infrastructure we can leverage for a check for this; IIRC previously OF was using deployment readiness for this check, but we were seeing that the endpoint would sometimes not be up-to-date in that timespan, because when scaling to zero the endpoint can't really be ready before or at the same time as the pod, so I think the intent figured that if the endpoint was online we can assume readiness with minimal extra checks.

Can you think of a better way? Maybe checking pod readiness that corresponds to that endpoint before trying to make the request? Issue with that is that once you start doing enough checks, you might as well just retry, but then that might make the OF-level retry logic and network-level retry logic a bit more messy.

**Comment by alexellis** [comment]
There are two modes of invocation, we started with one which was that the gateway would invoke a function based upon the URL using a convention of `http://gateway.openfaas:8080/function/NAME` => `http://NAME.namespace:8080`

directFunctions=true

```
Ingress => GW => K8s service name
```

directFunctions=false

```
Ingress => GW => Faas-netes => Active Endpoint IP
```

Later, we found that the Kubernetes service did no form of load-balancing for us, it was extremely sticky, so we created a new mode which forwarded the invocation on to the OpenFaaS controller called "faas-netes". faas-netes monitors a list of active endpoints and then looks up an Endpoint IP for invocation similar to `http://10.0.1.100:8080` - the [invocation is then made via a proxy](https://github.com/openfaas/faas-provider/blob/master/proxy/proxy.go)

The first mode is "directFunctions=true` because the gateway directly invokes the service, the `directFunctions=false` defers to the [faas-provider which is abstracted](https://github.com/openfaas/faas-netes/blob/master/main.go#L219).

For service meshes, we use `directFunctions=true` so that the sidecar can do the load-balancing.

However, during scale from zero, we have code like this:

```
while replicas < 1
  try to request min_replicas

while ready_replicas < 1
  wait
```

The above works relatively well with `directFunctions=false` and the endpoint monitoring code in faas-netes. @welteki was unable to reproduce any issues with a local KinD cluster, however a distributed multi-node cluster may show up errors.

Readiness is determined by "AvailableReplicas" > 0 on the function's deployment:

https://github.com/openfaas/faas-netes/blob/e63dbfae4515f128c30dd55686fa312282016fb9/pkg/handlers/replica_reader.go#L23

https://github.com/openfaas/faas-netes/blob/e63dbfae4515f128c30dd55686fa312282016fb9/pkg/k8s/function_status.go#L29

Here is the IP resolution:

https://github.com/openfaas/faas-netes/blob/e63dbfae4515f128c30dd55686fa312282016fb9/pkg/k8s/proxy.go#L57

With Istio is set to `directFunctions=true` and the above code isn't exercised.

When we heard of the issue with Istio, I made a patch which changed this logic to look for Active endpoints for the service instead, which didn't improve things for Kevin.

So it seems like, even if the Available Replicas on the deployment are > 1 or the Service has at least one active endpoint available for the function, Istio may still not be ready and could cause a 503 error.

That makes me wonder whether we need to bind to the Istio clientset, to ask its own API whether a Service is ready?

Alex

**Comment by howardjohn** [comment]
Kevin - I am still a bit unclear which component you are seeing the error in. There are a lot of components here and I don't know which have Istio sidecars since I am not as familiar with openfaas.

In general, this is not an Istio specific issue. You may see it in Istio but not <non Istio alternative>, but if so that is just an issue of "eventual consistency" being slower with Istio than X. Kubernetes makes no guarantee that Endpoints object state (or any object state) exactly matches the networking paths programming at any given time; there is always some delay. Istio does not expose any API to determine if it has been programmed, either.
I think knative solves this by probing

**Comment by kevin-lindsay-1** [comment]
> I am still a bit unclear which component you are seeing the error in. There are a lot of components here and I don't know which have Istio sidecars since I am not as familiar with openfaas.

I've tried it in 2 main configurations:
```
[pod] gateway w/ sidecar -> [service] fn -> [pod] fn w/ sidecar
[pod] gateway w/ sidecar -> [service] fn -> [pod] fn w/o sidecar
```

Since I can see the `503 no healthy upstream` (which is a known Istio HTTP response shape) in both attempts (OF uses a 502), I would say that this is coming from the sidecar on the gateway.

I think the issue may be stemming from the sidecar having internal state as to whether or not the service is ready. OF detects that the service is ready before the sidecar, tries to make the request, the sidecar has yet to update its readiness for that service, and responds that it is not available. I'm obviously not authoritative on this vs the two of you on your respective components.

**Comment by kevin-lindsay-1** [comment]
Let's say we could optionally delay the request when scaling from zero, is there a specific amount of time that the sidecar waits before we should expect its state on a particular service to be updated?

For example, if it checked once every 5 seconds, could we just add a delay of 5 seconds when performing a request that scales from zero, and by default it's set to `0ms`? This delay would only happen on initial scale from zero, and therefore be opt-in and could potentially cover a number of different cases/environmental conditions that might cause unexpected behavior when scaling from zero.

**Comment by alexellis** [comment]
I added a loop to probe the health endpoint after scale from zero, the test image is: `docker.io/alexellis2/gateway:0.0.13`, feel free to have a play with it.

**Comment by kevin-lindsay-1** [comment]
This appears to resolve this issue for our previous test cases, and I'd say it covers this issue 99%.

However, I notice that if I send a _large_ amount of requests at once concurrently, I will see roughly a handful of 503s all during a very small window of time. This is literally for a thousand concurrent requests, but I do find it strange that all of these would have the exact same status code at the exact same time, presumably after the probe succeeded, and then 

While I think this might be a bit excessive of a test, when I do this when it's not scaling from 0, I just get regular 429s, no 503s. Seems like there's still a small window where the gateway can forward things before the fn is fully ready?

```
// scale events and function spec being logged
// looks like more than one scale request going out, but that's not in scope for this. scale succeeds.
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:37 SetReplicas [sleep.openfaas-fn] took: 0.120173s
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:37 [Scale]: 0/20, error: unable to scale function [sleep], err: error scaling HTTP code 500, http://127.0.0.1:8081/system/scale-function/sleep?namespace=openfaas-fn
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:37 [Scale]: 0/20, error: unable to scale function [sleep], err: error scaling HTTP code 500, http://127.0.0.1:8081/system/scale-function/sleep?namespace=openfaas-fn
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:37 [Scale]: 0/20, error: unable to scale function [sleep], err: error scaling HTTP code 500, http://127.0.0.1:8081/system/scale-function/sleep?namespace=openfaas-fn
gateway-6f7b5b97cd-26pv7 operator I0527 13:57:38.278935       1 request.go:668] Waited for 1.009227066s due to client-side throttling, not priority and fairness, request: GET:https://172.17.0.1:443/apis/openfaas.com/v1/namespaces/openfaas-fn/functions/sleep
// 503s start
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:40 Forwarded [GET] to /function/sleep - [503] - 0.038291s seconds
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:40 Forwarded [GET] to /function/sleep - [503] - 0.003495s seconds
... // hidden; 503s repeat ~15x
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:40 Forwarded [GET] to /function/sleep - [503] - 0.001479s seconds
// 503s end, normal responses start
// a few 429s at the start, it seems?
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:40 Forwarded [GET] to /function/sleep - [429] - 0.004701s seconds
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:40 Forwarded [GET] to /function/sleep - [429] - 0.004532s seconds
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:40 Forwarded [GET] to /function/sleep - [429] - 0.003385s seconds
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:40 Forwarded [GET] to /function/sleep - [429] - 0.002879s seconds
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:40 Forwarded [GET] to /function/sleep - [200] - 0.011315s seconds
gateway-6f7b5b97cd-26pv7 gateway 2022/05/27 13:57:40 Forwarded [GET] to /function/sleep - [200] - 0.002955s seconds
... // more normal responses
```

**Comment by alexellis** [comment]
The Pro queue-worker was not retrying for 503s, so I've added this for the time being and it should "mop up" any additional errors that may appear when using asynchronous invocations.

See also: 577a9f63
