### ISSUE TITLE
Question about OpenFaaS Pro features 

### ISSUE THREAD

**Issue by podilavenky** [openfaas/faas#1742]
I am doing poc on openfaas to present with in my organization. I deployed openfaas in AWS eks and used Fargate for worker nodes. I am trying achieve scale to zero feature using opensource version but in docs it showing scale to zero available in pro version. Can you please guide me how to achive scale to zero in openfaas.

**Comment by alexellis** [comment]
Hi please feel free to get in touch with us via openfaas.com/support 

Thanks again for your interest

**Comment by Zetanova** [comment]
I am new to OpenFaas and this was one of my first converses to try/deploy it.

What does exactly mean **NOT** to scale to zero?

Is only one watchdog for each inside the custom container running and waiting for a request 
then to execute the handler process?

Is this assumption correct:
If I found deploy 100 different functions then there would be 100 different container images 
running 100 watchdog processes and waiting for requests.

If the watchdog consumes 2-5MB memory this means 200-500MB memory overhead.

**Comment by Zetanova** [comment]
I answered my question myself, dotnet 6 and kestel will be initiated as singleton over the fo-watchdog

The issue with dotnet6 kestrel is, that it uses relative much memory,
to use many instances for a single function each can sum up fast.

@alexellis  I made now an request for a "call" on the above provided link.
The problem is that I don't like to "call" and I don't like 
to put my credit card data over the phone.

**Comment by alexellis** [comment]
Hi @Zetanova no business process that we have will ask for a credit card, where are you getting that idea from?

If you don't want to schedule a meeting about OpenFaaS Pro, then I understand and I'll close this issue. If you change your mind in the future, you know where we are.

Thanks for your interest.

Alex
