### ISSUE TITLE
Pricing Scenarios

### ISSUE THREAD

**Issue by OR13** [openfaas/faas#176]
Given the multitude of potential backend providers, it is desirable to develop a system for comparing operating costs across providers. 

## Expected Behaviour
Ideally there would be cost estimates for network, compute and storage bound functions.
A simple experiment on each provider should be able to provide function costs.
Assuming operating costs could be parametrized, a pricing calculator could be constructed to assist users in selecting the backend provider best suited for their use case.

## Current Behaviour
Currently, it is difficult to understand what the operating cost will be due to differences in the infrastructure as a service costs across providers. Since one of the main benefits of cloud functions is their ability to avoid continuous operation costs and capture true utilization costs, it would be excellent if consumers could know the cost of function execution before they purchase the associated service.

## Possible Solution
Design a sample service for testing costs for network, compute and storage bound functions.
Perform a test of each service on a given provider and measure the cost.
Report the results, so a model or price calculator can be constructed.
Ideally this could be done without actually costing the tester money, or a given provider could assist by providing compensation for the test.

## Context
I'm designing a secure multiparty computation product where consumers of the service purchase executions of a function at the operating cost plus a markup chosen by the service provider. I want consumers to be confident that the markup is not egregious, and have confidence in the transparency of the pricing of the service.

## Your Environment

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

**Comment by johnmccabe** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
Derek add label: revisit

**Comment by alexellis** [comment]
This would require a significant amount of consulting and analysis - and I suspect it would be a moving target also. Also worth nothing that the spot instance market with AWS, Packet and others could easily provide a much cheaper back-end for some of the stack - particularly functions.

**Comment by alexellis** [comment]
Derek add label: priority/low

**Comment by alias1** [comment]
While this would likely take a pile of effort, as @alexellis mentioned, it's something that would be pretty cool IMO.

I wonder if this information could be 'derived' through some base pricing, and some more detailed metrics collected around the function execution.

For example, it might not be possible/practical to say the exact cost to run on EC2/similar given spot pricing/changes/etc. But it might be a nice feature (or at the very least a research project/blog post) to compare what running a function on OpenFaaS is like in comparison to AWS lambda/similar providers.

I know of at least one other project (https://github.com/apex/apex) that has done similar, though it was AWS Lambda specific. The following isn't a great example since i've barely run the function.. but..

```
⇒  apex metrics
  gobuster
    total cost: $0.00
    invocations: 0 ($0.00)
    duration: 0s ($0.00)
    throttles: 0
    errors: 0
    memory: 128
```

Related:

* http://apex.run/#viewing-metrics
* https://github.com/apex/apex/tree/master/metrics
* https://github.com/apex/apex/blob/master/cost/cost.go

**Comment by alexellis** [comment]
Closing and marking #revisit for follow-up at a later date.
