### ISSUE TITLE
Is it possible to output a file to download as a output of a function?

### ISSUE THREAD

**Issue by breadjuice** [openfaas/faas#1798]
If it's possible, where to find a guidance about it? thanks for your help.

**Comment by alexellis** [comment]
Hi @breadjuice yes no problem.

We explain how in this free course => https://www.openfaas.com/blog/introduction-to-serverless-linuxfoundation/

Since you didn't take the time to fill out the issue template with a specific example, we're unable to give you a fine-grained, exacting response, but you will get the answers you need in the course!

Alex
