### ISSUE TITLE
Proposal: Kafka queue-worker

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#234]
In a similar vein to [openfaas/nats-queue-worker](https://github.com/openfaas/nats-queue-worker), we should support Kafka (initially a set topic/partition) as a back-end for asynchronous process and model the NATS Streaming implementation.

Notes:
* Kafka runs its own cluster with zookeeper as an additional dependency
* Kafka complexity is several times greater than NATS Streaming
* Needs a new repo i.e. openfaas/kafka-queue-worker
* Changes to main.go/server.go in the faas repo
* Changes to the async-function route handler

**Comment by alexellis** [comment]
Derek add label: hacktoberfest

**Comment by johnmccabe** [comment]
@kinghuang is this something you'd be interested in

**Comment by VitorFalcao** [comment]
@alexellis Could I work on this? If yes, could you give me some pointers? This seems to be an awesome feature.

**Comment by alexellis** [comment]
Stay tuned.. we may have something from one our contributors coming around this

**Comment by StevenACoffman** [comment]
So, kubeless integrates kafka. It's also written in golang. Is there any interest in collaborating?

**Comment by yglcode** [comment]
as an learning exercise, i added initial code to use kafka, along the path of minimal impact:

* follow alex's suggestions, current code/flow for nats queue worker, add code in gateway and add kafka_queue_worker repository.

* add docker-compose.kafka-queue.yml to bring up zookeeper & kafka nodes in swarm together with gateway and kafka-queue-worker.

* to avoid tool-chain change, use Shopify sarama package instead of confluent-kafka-go package. while the latter quarantees the latest features, it introduces dependencies on C/C++ librdkafka library. we may not be able to build static linked binaries and have to use [alpine images with librdkafka built in](http://github.com/yglcode/alpine-kafka-go).

links:
[kafka_queue_worker branch](http://github.com/yglcode/faas).
[kafka-queue-worker repo](http://github.com/yglcode/kafka-queue-worker).

any suggestions? i am happy to help share and merge the code.

**Comment by alexellis** [comment]
Thank you for all the work on this. It was used in the Kafka-connector, but the gateway still uses NATS Streaming for Async. We may revisit in the future depending on appetite from users.
