### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#236]
We've created and marked some of the issues as #hacktoberfest across all the repos in the organisation.

If contributors have ideas please add them in this thread for consideration as #hacktoberfest items. Ideas include:

* UI tweaks
* PoCs - i.e. helping the faas-ecs implementation move on
* Blogging / guides
* CLI enhancements

and whatever else you have in mind. 

Open issues:

* https://github.com/openfaas/faas/issues/
* https://github.com/openfaas/faas-cli/issues/
* https://github.com/openfaas/faas-netes/issues/

**Comment by rgee0** [comment]
Function invocation scheduler.
UI enhancements to configure such a scheduler.

**Comment by austinfrey** [comment]
@rgee0 i had a preliminary function scheduler working with redis if you wanted to check it out https://github.com/austinfrey/skej

**Comment by vielmetti** [comment]
Multiarch support, so that OpenFAAS runs everywhere Docker runs. Hopefully some IBM'ers could be called into service to get it running on Power and s390, and I'm happy to help with the armhf and arm64 side of things. 

The main blocker for this one is https://github.com/gliderlabs/docker-alpine/issues/304 which is being addressed by https://github.com/gliderlabs/docker-alpine/pull/337 which is native multi-architecture Alpine support.

Would like to get @estesp and @tianon involved to speed this along.

**Comment by alexellis** [comment]
In terms of a scheduler - if we do make this, it should be a Golang service which is deployed alongside the gateway. We need to dig into why `cron` is discouraged in containers etc.

**Comment by alexellis** [comment]
I don't have access to IBM Power or s390 hardware, but armhf has support (with manual builds) and ARM64 is partially ported. I'd like to make the armhf builds automated which may involve paying for a Scaleway instance.

**Comment by scher200** [comment]
@alexellis https://github.com/dshearer/jobber might do the cronjob alike thing.

**Comment by alexellis** [comment]
Thanks or the suggestion @scher200

**Comment by scher200** [comment]
@alexellis I am not a go beginner, but I am willing to try.

**Comment by rgee0** [comment]
Derek close

**Comment by alexellis** [comment]
Thank you for the admin Richard. Any take aways @rgee0?
