### ISSUE TITLE
How to integrate 3rd libs that have log or debug with themself

### ISSUE THREAD

**Issue by leenux** [openfaas/faas#244]
If the 3rd libs's debug log output to console,Hope to ignore these console output.
How to deal with it? 
No inspiration or ideas were found with #11 #157 #53

**Comment by e-beach** [comment]
I don’t think openfaas can deal with this problem, since we rely on your handler to control console output. There are often tools to suppress console output in the language you are dealing with (e.g., in
 [JavaScript](https://stackoverflow.com/questions/1215392/how-to-quickly-and-conveniently-disable-all-console-log-statements-in-my-code)).
Alternatively you can write a wrapper script around your handler that

1. redirects stdout to another /dev/null
2. passes a fifo or file for your handler to write intended output
3. cat fifo to stdout in the wrapper

**Comment by leenux** [comment]
@e-beach 
Hi,
Thank you.
It looks like that need to switch between redirection and normal output repeatedly.

**Comment by alexellis** [comment]
All messages written to `stdout` and `stderr` will be returned as part of the function response. There is a possibility that we can add a "mode" to only return data printed to `stdout`. What library are you struggling with @leenux ?

**Comment by alexellis** [comment]
@leenux this issue has been idle 7 days so we'll close, but feel free to keep commenting.

**Comment by leenux** [comment]
@alexellis 
Sorry the echo delayed  because holiday.
The libs is docker container's log 3rd lib.
It is excited for this mode to only return data printed to  stdout  and allow  stderr  to be only printed to the logs.Wait for this mode to join.
Thank you.
