### ISSUE TITLE
Add minimal deploy script and Docker Compose files

### ISSUE THREAD

**Issue by rorpage** [openfaas/faas#478]
As a frequent user of the project, setting up a new instance that includes all of the samples functions is redundant.

## Expected Behaviour
A user issues a command such as `./deploy_stack_minimal.sh` and only the necessary functions are deployed (gateway, monitoring, etc.)

## Current Behaviour
A user can issue a `./deploy_stack.sh` but then half a dozen or so sample functions are included.

## Possible Solution
Create a `minimal` script and `docker-compose-minimal.yml` file for both ARM and non-ARM architectures.

**Comment by rorpage** [comment]
Derek add tag: enhancement

**Comment by rorpage** [comment]
Derek add label: enhancement

**Comment by rorpage** [comment]
Derek add label: skill/beginner

**Comment by rgee0** [comment]
@rorpage I'd suggest that rather than have multiple `.sh` scripts for different deployment states we should aim to have one `deploy.sh` that accepts arguments such as `minimal`, `with samples`, `extended`.  One of the options should be the default - I think there was mention at some point that extended might become that.

**Comment by dungeonmaster18** [comment]
Hey @rgee0, by minimal you mean no sample functions and by with_sample you mean functions included. If I am wrong till here please correct me. Now I couldn't understand what did you mean by extended?

**Comment by rgee0** [comment]
@dungeonmaster18 you'll notice that it was @rorpage introduced the idea of minimal.  my interpretation of minimal was an install with the bare minimum required for OpenFaaS to function.  With_samples would effectively be what was the standard install which included samples and not the async elements. Extended existed previously as a means to include the async components but now it has become the standard on x86 and so is only available on ARM.

Maybe there would be just the two options

**Comment by dungeonmaster18** [comment]
**Proposal**
* Let's add a minimal docker-compose file without any sample functions.
* Then the setup will change from ```./deploy-stack.sh``` to ```./deploy-stack.sh minimal``` and ```./deploy-stack.sh with_sample```. Same goes to arm64 and armhf as well.

CC / @alexellis @rgee0 for approval. I can work on this if it gets approved by you guys.

**Comment by rorpage** [comment]
Are you thinking you'd have it default to `extended` then if no args are passed in?

**Comment by dungeonmaster18** [comment]
for no arguments I was thinking of let's install all the samples.

**Comment by itscaro** [comment]
Up vote for removing all samples

**Comment by rorpage** [comment]
Same. Consistency sounds good to me.

**Comment by rgee0** [comment]
OK, so it reads to me like we are saying that the default mode of deployment should be standardised with sample functions pulled out of the deployments.  To be consistent with the project value of portability this should provide the same experience across hardware types too (currently there are 2 yaml files for `armhf`).  The deploy script should also be merged to correctly deploy based on hardware type #321 can be reopened or used for a steer.

As part of the rationalisation of the `armhf` compose files please note the functions that are being removed and log them into a new issue so that these can be worked through and added to the store idc.

**Comment by alexellis** [comment]
We need to move this forward, it's been sitting for 4 months. Please can someone on the thread volunteer?

**Comment by alexellis** [comment]
We need to update everywhere that references and mentions these sample functions including:

* The TestDrive (Markdown + docs.openfaas.com) and any other Markdown files
* Anything on docs.openfaas.com
* Suggest which blogs need editing that use the samples

Then:

Create a new YAML file to represent the missing functions (ideally in a stack.yml format if possible)

This should not be a duplication of docker-compose.yml - but something that can be run after the main stack (optionally).

**Comment by Warlord77** [comment]
Hi , Is this is issue open . I would like to work on this

**Comment by alexellis** [comment]
Derek close: fixed
