### ISSUE TITLE
Proposal: Move UI out of gateway

### ISSUE THREAD

**Issue by BurtonR** [openfaas/faas#581]
Discussion about moving the UI code base to a separate image that could be developed/released independent of the gateway and would not be required for OpenFaaS cluster deployment

I imagine the UI as more of a development/testing component of the OpenFaaS framework and as such, believe it should not be included if deploying to a production environment

## Expected Behaviour

The UI should be a separate component that can be excluded, and released separate from the gateway

## Current Behaviour

When deploying the gateway, the UI is bundled with it and cannot be separated

## Possible Solution

Create a separate image with only the UI pieces

## Context

Changes to the UI require a new version of the gateway.
Working on the UI codebase is not straightforward
The UI is not needed in a production environment where functions would be managed by CI/CD or other tools

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

I understand that this would not be a high priority. 

Putting this out there to see if anyone else agrees.

**Comment by BurtonR** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
> Changes to the UI require a new version of the gateway.

Correct - they are often coupled together - i.e. the gateway API and gateway UI should "agree" to a contract, this keeps them up to date.

> Working on the UI codebase is not straightforward

In what way? The code is static HTML built into a container, it's the simplest form of a website.

> The UI is not needed in a production environment where functions would be managed by CI/CD or other tools

The UI is a dashboard which is just as useful in production as development.  It may not be used to deploy functions, but the same argument can be made of the Kubernetes dashboard - it's very useful for an overview of the system.

Having the HTML code present in the gateway adds no overhead and does not expose any additional risk since it makes use of the existing well-documented REST endpoints.

My position is that I won't be giving the OK to break out the UI into yet another Docker container, repo and image until there are clear pros which outweigh whatever cons exist of keeping the two together. The team making active code contributions is too small to deal with the additional overhead.
 
Remember that every additional version of a Docker image requires a change in 7 places including additional testing.

* Swarm - 64-bit compose, ARM compose, ARM64 compose
* Kubernetes - Helm, 64-bit YAML, ARM YAML and ARM64 YAML

The time that the UI may graduate outside of the API Gateway image may be if we need a complex build-chain for React or similar and if coupling the two together presents some kind of blocker.

I'll close the issue, feel free to comment on it.

**Comment by BurtonR** [comment]
I can understand that there are not enough pros, and not compelling enough cons with the current process to do this work at this time.

To bring up some counter-points to your points:

> Correct - they are often coupled together - i.e. the gateway API and gateway UI should "agree" to a contract, this keeps them up to date.
* Keeping them in sync is important, but making a change to the layout, or UX of the UI should not require a new release of the API since that hasn't actually changed and would be confusing.
* To counter my own point, that hasn't happened yet...

> Working on the UI codebase is not straightforward
* For this I'm referring to the [HACK.md](https://github.com/openfaas/faas/blob/master/contrib/HACK.md) file. I expect a simple `npm start` or `./index.html` when working on a UI project

> The UI is a dashboard which is just as useful in production as development. It may not be used to deploy functions, but the same argument can be made of the Kubernetes dashboard - it's very useful for an overview of the system. Use of the UI is optional.
* The current UI is focused mostly on executing functions as noted by the ~80% of screen taken by the "Invoke Function" section. While it is true you _can_ manage functions (deploy, delete, etc.) that's not the focus. Maybe down the road, we could add some charts and an overview of all the functions together. More of a "dashboard" view rather than an execution view...
* Referring to the Kubernetes dashboard, this is a separate container that can, or can not, be deployed. It's not build into k8s. That seems to more solidify my proposal :)

> Remember that every additional version of a Docker image requires a change in 7 places including additional testing
* This is an interesting problem... I admit I hadn't thought of the ARM side of things.
* UI Unit tests, and using a standardized tag name could help in this (`latest` vs `1.1.2` for example), although not bullet-proof by any means

> The time that the UI may graduate outside of the API Gateway image may be if we need a complex build-chain for React or similar and if coupling the two together presents some kind of blocker.
* This makes perfect sense. The current UI, using just AngularJS doesn't really require all the infrastructure around it that a more complex UI would. 

I understand your desire to not move forward with this right now. You do bring up some good points that would need to either be discussed more, or have a _real_ need for, before moving forward with a change like this.

Thanks!

**Comment by kenfdev** [comment]
I'd like to leave some comments about this, too.

> Keeping them in sync is important, but making a change to the layout, or UX of the UI should not require a new release of the API since that hasn't actually changed and would be confusing.

I understand this circumstance but separating the image may be too much for now. As Alex points out, the 'contract' part is much easier to be achieved if they are in the same image. One could update only the gateway and forget the UI image and could break the functionality because of the API difference (well, we should think about backwards compatibility at the first place though).

> For this I'm referring to the HACK.md file. I expect a simple npm start or ./index.html when working on a UI project

I agree with this. Currently I always mount my local `assets` to the gateway when I develop the UI which is not a really smooth experience. It would be much better if I could run a local version with `npm start` and proxy the requests to the gateway via webpack or something similar.

> The time that the UI may graduate outside of the API Gateway image may be if we need a complex build-chain for React or similar and if coupling the two together presents some kind of blocker.

This issue really depends on when we'll start the build-chain for the UI. Is it worth building a npm pipeline for the current AngularJS UI? That's a tough question.

> The current UI, using just AngularJS doesn't really require all the infrastructure around it that a more complex UI would.

Which makes me agree about this, too. Modern frameworks like React, Vue, Angular have a pipeline pretty much out of the box. Not sure of the current AngularJS but I don't think it's worth the effort at least for now.


Side Notes:
Some immediate pros I can think of about adding a pipeline is that we could cache bust the assets using the hashing functionality of webpack (not specific to webpack though). As @itscaro pointed out in #497 , the current gateway UI doesn't have cache busting. So adding or removing features in the JavaScript may lead to weird functionalities depending on how long the assets are being cached.
