### ISSUE TITLE
Can't delete function from the UI in play with docker.

### ISSUE THREAD

**Issue by Rillian-Grant** [openfaas/faas#586]
## Expected Behaviour

When you delete a function it disappears from the UI and the CLI.
## Current Behaviour

I can delete a function using the CLI but not with the UI.

## Steps to Reproduce (for bugs)

1. Follow the steps in TestDrive.md
2. Try to delete a function from the UI..

## Your Environment

# Note: this was done on play with docker.

**Comment by alexellis** [comment]
Thanks for reporting that. I'm not aware of any issues but will take a look.

**Comment by alexellis** [comment]
Derek add label: question

**Comment by rgee0** [comment]
Following the PWD directions in `testdrive.md` I have been able to delete sample functions and functions deployed from the store.  

Can you provide further details on how you were using the CLI. Ideally the steps to reproduce via the CLI.

**Comment by Rillian-Grant** [comment]
I can delete functions via the CLI using faas/faas-cli remove ...

With the web UI the popup box asking if you really want to delete the function pops up but when you click OK nothing happens.
I am using Google Chrome version 64

**Comment by rgee0** [comment]
I'm interested in the CLI in case you are deploying the function that you cannot delete in this way.  With the steps we can try to replicate and understand your question better.  

When using the UI:

What actually happens when you click the OK button? 
- Does it go away?  
- Do you get the success toaster?  

In the Network tab of dev tools do you see a DELETE request being made?  
- Does the request have a request payload?  
- What is in the payload?

This is how its performing for me on PWD:

![store_delete](https://user-images.githubusercontent.com/16418793/37554832-36befd6e-29d6-11e8-8250-d3e34c67e347.gif)

**Comment by Rillian-Grant** [comment]
The Box goes away
and I havent looked for the delete request

**Comment by alexellis** [comment]
@Rillian-Grant we ask for the issue template to be filled out **for a reason** - it gives us the context we need to reproduce the problem. You don't say if you're using Windows, Linux or Mac for your client.

I have Chrome version Version 65.0.3325.162 (Official Build) (64-bit) on my Mac. 

Delete works fine via PWD - same with 0.7.3.

Here's an idea - clear your browser cache and / or update your browser.

**Comment by alexellis** [comment]
We're unable to reproduce the issue. Please try the steps we mentioned above.

**Comment by Rillian-Grant** [comment]
OK thank you for your help.
