### ISSUE TITLE
Question about HTTP PATH in functions

### ISSUE THREAD

**Issue by yoanisgil** [openfaas/faas#622]
The new HTTP mode from `of-watchdog` opens the possibility to running more than one endpoint from the same application.  For instance, [this file](https://github.com/openfaas-incubator/python27-flask-template/blob/master/template/python27-flask/index.py) could actually contain more than one route. However it will require that the gateway forwards not only HTTP calls which matches the exact function path but also anything beyond the initial function path (`/functions/function-name/path/to/route`, `/functions/function-name/path/to-another-route`, etc).

The case for this is that it will soften the requirement for an API gateway in front of Openfaas. It could also reduce the amount of repeated code and boilerplate when developing an API that exposes a few endpoints.

I'm not exactly requesting this as a new feature but rather opening a conversation to see what thoughts people might have about it.

**Comment by BurtonR** [comment]
That's an interesting proposal, however adding routes and multiple paths goes against the concept of a _function_ as a service. Where each function has a single, short-lived, process. What you're describing is an API.

To address your concern over the repetitive boilerplate code, this is the reason for the templates. There is also the ability to create your own template and use that as the base of similar functions.

Also, because of the design of OpenFaaS, any language you use could benefit from shared code. If you have some code that needs to be executed in several functions, you could package that as a library and include it in the dependencies of the functions.

Alternatively, if you do need some sort of path, you could use custom headers, or a query string. Both of which are passed to the functions as environment variables. You  could use either of those in a switch statement and route the process that way.

**Comment by BurtonR** [comment]
Derek add label: question

**Comment by yoanisgil** [comment]
> That's an interesting proposal, however adding routes and multiple paths goes against the concept of a function as a service. Where each function has a single, short-lived, process. What you're describing is an API.

I could not agree more. I think I was heavily influenced from working with frameworks like Zappa that allows you to run a Python applications using AWS Lambda + API Gateway. But yeah, when there is that level of coupling/coherence between multiple functions then it's just an API.

Anyway, thanks for hints.

**Comment by alexellis** [comment]
Good suggestion. I've thought about it a number of times before. What do you think the benefit would be to using path over the query string, the body of the request or similar?

**Comment by yoanisgil** [comment]
I cannot really think of a technical benefit solution right now, but for sure it eases the integration with Frameworks such as Flask, Bottle or any framework where routes are declared by means of using annotations. Generally speaking I think it makes a developer life easier. It also allows for better separation of concerns and not having, yet, another routing mechanism in your function's entrypoint? I mean, let's take a look at both uses cases (query string and body). With the query string, and assuming that there are multiple execution endpoints, in order to be able to make calls like this:

- /function/api?name=get-users
- function/api?name=get-records

one would need to implement a handler alone these lines:

```python
def _get_users():
    return ['user1', 'user2']
def _get_records():
    return ['record1', 'record2']

def handle():
   function_name = get_function_name_from_env()  # Not sure how to implement this but you get the idea
   if function_name == 'get-users':
      return json.dumps(_get_users())
  if function_name == 'get-records':
      return json.dumps(_get_records())
  else:
      return {} # Return 404#?
```

Now, if the gateway were to forward everything that starts with a given prefix to a given function, then as a developer (and assuming that of-watchdog mode is set to HTTP), I could do this:

```python
from flask import Flask
from functions.get_users import handle

app = Flask(__name__)

@app.route("/get-users", methods=["GET"])
def get_users():
    return ['user-1', 'user-2']

@app.route("/get-records", methods=["GET"])
def get_users():
    return ['record-1', 'record-2']

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=False)
```

Now as @BurtonR mentioned this might go against the FaaS approach since well if you bundle a few endpoints together then it's no longer a function but rather an API. And at this point it just becomes a matter of packing and deploying your API.

Maybe approaches like the one taken by Zappa work pretty well when you're not managing your own infrastructure? Or when you infrastructure is big/complex enough that you need to abstract it's complexity away away from your developers?

**Comment by alexellis** [comment]
> I cannot really think of a technical benefit right now

I think this is probably why we don't need full HTTP Path support at this stage.

> I could do this:
>     app.run(host='0.0.0.0', port=5000, debug=False)

We don't want you to start a HTTP server and manage Flask. That's the point of abstracting this away to give a light-weight function handler without any unnecessary concerns.

Here are some more questions / thoughts:

* What are the benefits in a single function having multiple routes?
* At what stage does it become a regular microservice again?
* What happens when you don't invoke the function over HTTP?
  * i.e. an event such as an S3 bucket push or a Kafka/RabbitMQ topic is the trigger - how does it know what HTTP route to use?

There's nothing wrong with having modes or overrides for your function and you can achieve that in a number of ways through HTTP headers or a HTTP QueryString. Both work on the classic watchdog too.

**Comment by yoanisgil** [comment]
Yeah, all mentioned points are valid and I'm of the same mind when it comes to the fact that if a function is allowed to have multiple routes then ... well it's not longer a function but rather a micro-service. 

> We don't want you to start a HTTP server and manage Flask. That's the point of abstracting this away to give a light-weight function handler without any unnecessary concerns.

That is indeed an interesting comment. The reason I switched to HTTP mode was mainly because performance issues. In my current setup if I use the current `watchdog` my functions will incur in a performance penalty of something between 2x - 10x (when compared to the same code running on a docker container using Tornado). 

By switching to the new `watchdog` the performance I have observed is quite similar to my baseline, which is, again, a Docker container which serves a few HTTP endpoints using Tornado.

And yes, I will be more than happy to throw away HTTP mode if it only matches my baseline performance.

**Comment by alexellis** [comment]
I think you're misunderstanding what I'm saying.

As a developer in your function handler you should not try to bind to any HTTP ports at all.

See the Node and Python templates for of-watchdog for an example of what I mean.

Template | HTTP framework | Repo
-- | -- | --
Node.js | Express.js | https://github.com/openfaas-incubator/node8-express-template
Python 2.7 | Flask | https://github.com/openfaas-incubator/python27-flask-template
Golang | Go HTTP (stdlib ) | https://github.com/openfaas-incubator/golang-http-template

Alex

**Comment by yoanisgil** [comment]
The binding thing I got it from here:

https://github.com/openfaas-incubator/python27-flask-template/blob/master/template/python27-flask/index.py#L15

That's a port binding there.

**Comment by alexellis** [comment]
So do me a favour and generate a function then paste the handler here.

**Comment by yoanisgil** [comment]
My handler looks like this:

```python
import os

from flask import Flask
from functions.get_users.function import handle

app = Flask(__name__)


@app.route("/", methods=["GET"])
def main_route():
    return handle(os.environ['DATABASE_URL'])


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=False)
```

and this is the Dockerfile:

```Dockerfile
FROM python:3.6-alpine

RUN apk --no-cache add curl \
    && echo "Pulling watchdog binary from Github." \
    && curl -sSLf https://github.com/openfaas-incubator/of-watchdog/releases/download/0.2.3/of-watchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog \
    && apk del curl --no-cache

WORKDIR /srv/app

=ENV cgi_headers="true"
ENV mode="http"
ENV upstream_url="http://127.0.0.1:5000"

RUN pip install --upgrade pip && pip install --no-cache-dir setuptools && \
    pip install --no-cache-dir pipenv

COPY Pipfile Pipfile.lock /srv/app/

ARG PIPENV_INSTALL_ARGS=''

RUN PIP_NO_CACHE_DIR=false pipenv install --deploy --system $PIPENV_INSTALL_ARGS

COPY . /srv/app

HEALTHCHECK --interval=1s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"]
```

**Comment by alexellis** [comment]
The handler is as follows:

```python
def handle(req):
    """handle a request to the function
    Args:
        req (str): request body
    """

    return req
```

The handler is the official serverless abstraction used by all FaaS frameworks. Any templates should hide technical details away in the Dockerfile and entrypoint leaving what is effectively just a callback or a handler for the client.

The Python template based upon Flask will be extended to support more context like HTTP headers and status codes.

**Comment by yoanisgil** [comment]
I see. Thanks for letting me know :)

**Comment by alexellis** [comment]
The Node and Golang templates I linked to show how you can access HTTP state for more involved handlers.

**Comment by yoanisgil** [comment]
Yes sure. Let me know how I can help :).

**Comment by yoanisgil** [comment]
@alexellis is this what you were talking about:

https://github.com/openfaas-incubator/python-flask-template/compare/master...yoanisgil:modify-headers-status-code?expand=1

I still need to add a few test cases and implement the same functionality for Python2.7.

Please let me know what you think.

**Comment by alexellis** [comment]
That looks really good. Let's raise a PR and take it from there?

**Comment by alexellis** [comment]
Just avoid the word "utils" please 👍

**Comment by alexellis** [comment]
Derek close

**Comment by yoanisgil** [comment]
@alexellis will do. Yeah, I don't like it either but I just wanted to hack something real quick to get your input.

**Comment by telackey** [comment]
I know this is closed, but if I might bring it back to what @yoanisgil was saying in an earlier comment using the example of get-users/get-records.

In Lambda, one can do something like (using node as example):

`module.exports = {
     taskA: (event, context, callback) => { ... },
     taskB: (event, context, callback) => { ... }
};`

And (after appropriate configuration) invoke something like:

https://aws-generated-hostname/stage/taskA
https://aws-generated-hostname/stage/taskB

I think an aspect in the discussion above that deserves more attention (though was hinted at with Flask) is that if these are logically connected from the standpoint of the *client* there is value in them having a common base.  

If AWS forced the same kind of complete separation as OpenFaaS, a client application could end up needing to be configured with completely different URL for every single function call (It isn't important to go into the AWS-specific weeds on ways to avoid that, btw, I'm just using it as an example.).  That may make sense as long as I am invoking completely unrelated functions, but not if what I am doing is all logically connected (eg, for image manipulation, it hardly makes sense to have completely different endpoints for 'flip-vertical' vs 'flip-horizontal', not even for auto-scaling purposes).

Or put another way, there is an implicit namespacing aspect to all of this as well.

In OpenFaaS, unless I am missing something, instead of being able to do:

/function/image/flip-vertical
/function/image/flip-horizontal
...

I need deploy separate functions (with separate Docker images, YAML...) and emulate a kind of namespace myself by using a common prefix the function names.  Something like:

/function/image__flip-vertical
/function/image__flip-horizontal

Obviously one could use a query string for that simple case, but I have a few observations:

1) Paths may not be strictly required if one has the perspective that all functions are being developed exclusively for OpenFaaS, but if you want developers to be able to move their code between OpenFaaS and Lambda, Google Cloud, etc., not allowing paths makes their life a lot harder.  It also artificially constrains developers from accessing features of frameworks like Flask, ExpressJS, etc. they might otherwise use.

2) The namespace problem alone presents an issue.  Even if full support of (1) were not done, it would sure make life easier to deploy functions into a namespace so that one could have <namespace>/<funcname>.  It would also allow for using short, simple function names like 'status' and 'test' that would otherwise be ambiguous or easily lead to collisions.

3) In theory, absolutely everything could be done with query strings, but there are a lot of valid reasons not to rely exclusively on query strings.  I can't help but observe that OpenFaaS's own API Gateway code does not use a query string but a path parameter for the function name...

At the end of the day, my suggestion is that once you've got the information necessary to match the incoming request to the function that needs to be invoked, pass the remainder of both the path and the query string along, letting the application developer decide which is the most suitable way to get input for their case.

**Comment by telackey** [comment]
As a quick update to the above, I made some draft changes to the API Gateway and of-watchdog to support passing the path through.  It is working nicely with node8-express.

At least in concept, are these changes something you would think about integrating?

**Comment by alexellis** [comment]
I have already made a change / PR to support path in of-watchdog, but it is not merged since the templates for of-watchdog do not yet support a path.

The gateway has a deterministic route rathe than a wildcard route, and a wildcard route would be needed to pass an arbitrary path through.

**Comment by telackey** [comment]
@alexellis 

As an update, I made a proposal with a couple of proof-of-concept changes to `of-watchdog` and the `API Gateway`.  The proposal is here: https://github.com/openfaas/faas/issues/716

**Comment by telackey** [comment]
As regards the template, this is _not_ something I mentioned in the proposal I made, but I construct the routes dynamically from the `handler.js` exports, with `root` ending up as '/':

```
if (isObject(handler)) {
    _.forOwn(handler, function(value, key) {
        if (_.isFunction(value)) {
            if ('root' === key) {
                console.log("Dynamically registered route: /");
                app.get('/', value);
                app.post('/', value);
            } else {
                console.log("Dynamically registered route: /" +  key);
                app.post('/' + key, value);
                app.get('/' + key, value);
            }
        }
    });
} else {
    console.log("Registered catch-all route: /*");
    app.get('/*', handler);
    app.post('/*', handler);
}
```

**Comment by alexellis** [comment]
To be fair the change would be just:

From:


```
  app.get('/', handler);
  app.post('/', handler);
```

to:

```
  app.get('/*', handler);
  app.post('/*', handler);
```
