### ISSUE TITLE
Proposal: set replicas to zero in Prometheus when deleting a function

### ISSUE THREAD

**Issue by CuZn13** [openfaas/faas#697]
# Title

When deleting a function, notify prometheus to set replicasCounter to 0

Delete a function, but still show one in prometheus. My approach is to add a deleteProxyHandler  add a method to metrics.go. Set replicasCounter to 0 when deleting a function

`func MakeDeleteFunctionProxyHandler(proxy *types.HTTPClientReverseProxy, metrics metrics.MetricOptions, baseURLResolver BaseURLResolver) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		baseURL := baseURLResolver.Resolve(r)
		body, _ := ioutil.ReadAll(r.Body)
		req:=requests.DeleteFunctionRequest{}
		json.Unmarshal(body, &req)
		delete(proxy.Client,baseURL,req.FunctionName,metrics)
	}
}

func delete(proxyClient *http.Client,baseURL string,functionName string,metrics metrics.MetricOptions){
	str :=make(map[string]string)
	str["functionName"]=functionName
	reqBytes, _ := json.Marshal(&str)
	reader := bytes.NewReader(reqBytes)
	request, _ := http.NewRequest(http.MethodDelete, baseURL+"/system/functions",reader)
	request.Header.Set("Content-Type", "application/json")
	_,err:=proxyClient.Do(request)
	if err==nil{
		log.Printf("delete functon [%s] is ok",functionName)
		trackFunctionStop(metrics,functionName)
	}
}

func trackFunctionStop(metrics metrics.MetricOptions, name string) {
	metrics.ServiceReplicasCounter.
		WithLabelValues(name).
		Set(float64(0))
}`

**Comment by alexellis** [comment]
Hi I think this sounds like a good approach. Thanks for using OpenFaaS and for logging the issue. 

Let's get another opinion and then look at moving forward with a solution and fix. 

Alex

**Comment by kenfdev** [comment]
Thank you for pointing this out @CuZn13 . This looks nice.  In addition, imo we should continue using the logic of the `MakeForwardingProxyHandler` so that we don't break the original functionality and not to duplicate code.

Something like the following:

```
func MakeDeleteFunctionProxyHandler(proxy *types.HTTPClientReverseProxy, notifiers []HTTPNotifier, baseURLResolver BaseURLResolver, metricsOptions metrics.MetricOptions) http.HandlerFunc {
	fph := MakeForwardingProxyHandler(proxy, notifiers, baseURLResolver)
	return func(w http.ResponseWriter, r *http.Request) {
		fph(w, r)
                // Decorate the original MakeForwardingProxyHandler by adding logic afterwards
		body, _ := ioutil.ReadAll(r.Body)
		req := requests.DeleteFunctionRequest{}
		json.Unmarshal(body, &req)

		trackFunctionStop(metricsOptions, req.FunctionName)
	}
}

func trackFunctionStop(metrics metrics.MetricOptions, name string) {
	metrics.ServiceReplicasCounter.
		WithLabelValues(name).
		Set(float64(0))
}
```

1 caveat I already know is that, since the above request can't realize if the forwarded request succeeded or failed, it will always set the replicasCounter to 0.  In that case, the `externalWatcher` (https://github.com/openfaas/faas/blob/master/gateway/metrics/externalwatcher.go#L60) should update the count but still, it may not be clean enough.

**Comment by kenfdev** [comment]
Sure, I'll take it. Thinking about how I could unit test (or maybe it's more an integration test) the prometheus metrics.  Since it's currently difficult to inject a mock,  I'm searching if there's any helpers provided by the prometheus library to assert the metrics.
In addition, I've thought about adding integration tests to the `deletefunction_test.go`, but wasn't sure if it's worth waiting around 5 secs to wait for the metrics to show up via the prometheus HTTP API.

**Comment by alexellis** [comment]
Update from @kenfdev - new version of the PR is coming with the `Collector` interface in Prometheus. cc @stefanprodan
