### ISSUE TITLE
README: PWD link leads to page that errors out

### ISSUE THREAD

**Issue by elimisteve** [openfaas/faas#711]
## Expected Behaviour

http://play-with-docker.com/?stack=https://raw.githubusercontent.com/openfaas/faas/master/docker-compose.yml&stack_name=func , a URL in `README.md`, should allow me to spin up OpenFaaS and play around with it.

## Current Behaviour

https://labs.play-with-docker.com/p/bcat9e8qr900009ftkk0 displays error that either shows that the config didn't work, on at least displays a misleading error message.

## Possible Solution

If this is not a fatel error, clarify in the README that it isn't, perhaps?  Preferably you could add a 

## Steps to Reproduce (for bugs)

1. Visit http://play-with-docker.com/?stack=https://raw.githubusercontent.com/openfaas/faas/master/docker-compose.yml&stack_name=func
2. Log in if you haven't already
3. Click Start > Docker
4. Look at your screen until you see the erroring-out CLI output:

![screenshot-docker-playwithdocker-openfaas-screenshot_2018-06-04_17-12-46](https://user-images.githubusercontent.com/139603/40948117-491ad270-681b-11e8-877b-6071cf6622fa.png)

## Context

I'm checking out OpenFaaS for the first time after hearing about it through a Meetup announcement.

## Your Environment

N/A

**Comment by elimisteve** [comment]
On second glance, maybe the PWD deploy _did_ work?...  It complained about a .yml file not being present.  I _was_ able to SSH into the machine though.  I don't know what I was supposed to be able to do after that.

But if PWD doesn't deploy OpenFaaS in a functioning (no pun intended) way, consider removing the PWD deploy button from `README.md`.

> You can still try openfass in PWD by manually cloning the repo and running docker stack deploy command.

Good to know, and something that should also probably go in the README :-).

**Comment by alexellis** [comment]
@elimisteve it's been added and removed half a dozen times over the last year depending on whether PWS is working or not.

@marcosnils it sounds like we'll have to remove the one-click button because we do need to use Swarm config files. This is a common use-case so I'd recommend re-visiting it on your backlog. It will be even more relevant with play-with-kubernetes where many projects use YAML definitions with config maps and secrets.

I'd be happy for someone to raise a PR to remove the button and just state how to operate Play-With-Docker in the "manual" sense. Add instance / Swarm init / join etc.

cc @BurtonR @ericstoekl for working on this

Alex

**Comment by marcosnils** [comment]
SGTM!.

**Comment by alexellis** [comment]
This also needs modifying over in the openfaas/docs repo: http://docs.openfaas.com/deployment/#docker-playground

Alex

**Comment by BurtonR** [comment]
I can remove that button and write up a "how to play with OpenFaas on Play-With-Docker". That is my go-to option for testing PRs and features.

**Comment by alexellis** [comment]
Sounds great.

**Comment by BurtonR** [comment]
@elimisteve  and @marcosnils  check out the new Docker Playground docs site for a detailed guide on deploying to PWD manually: http://docs.openfaas.com/deployment/play-with-docker/

**Comment by marcosnils** [comment]
LGTM!. Nice work @BurtonR .
