### ISSUE TITLE
Proposal: Marshal headers in CGI standard

### ISSUE THREAD

**Issue by info2000** [openfaas/faas#750]
The actual http headers syntax don't follow the usual syntax

## Expected Behaviour
This is an example of how are now in nginx and http
 [HTTP_COOKIE] => metaUUID=MjEzLjI3LjIyNS4xNzB8YjhhYTE2Y2IyZjgyZWRmZjgzNTQwYzRjZTAwYTU1NTc%3D
    [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_CONNECTION] => keep-alive
    [HTTP_HOST] => rcpt.tsapx.net
   [DOCUMENT_ROOT] => /var/nginx/tsapx.net
    [DOCUMENT_URI] => /opcache.php
    [REQUEST_URI] => /opcache.php?abc=1
    [SCRIPT_NAME] => /opcache.php
 [SERVER_NAME] => tsapx.net
    [SERVER_PORT] => 443
    [SERVER_ADDR] => 192.99.222.30
  [SCRIPT_FILENAME] => /var/nginx/tsapx.net/opcache.php
    [CONTENT_LENGTH] => 
    [CONTENT_TYPE] => 
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => abc=1
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => /opcache.php

## Current Behaviour
    [Http_User_Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
    [Http_Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
    [Http_Accept_Language] => en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7
    [Http_Cache_Control] => max-age=0
    [Http_Connection] => keep-alive
    [Http_Cookie] => _ga=GA1.1.1709874416.1531005813; _gid=GA1.1.27171284.1531005813
    [Http_Upgrade_Insecure_Requests] => 1
    [Http_X_Call_Id] => eade4c3b-1e20-411f-b25b-f191e9d1db1e
    [Http_X_Forwarded_For] => 10.255.0.2:54732
    [Http_Accept_Encoding] => gzip, deflate
    [Http_X_Start_Time] => 1531091263999609717
    [Http_Method] => GET
    [Http_Query] => a=1
    [PHP_SELF] => index.php
    [SCRIPT_NAME] => index.php
    [SCRIPT_FILENAME] => index.php
    [PATH_TRANSLATED] => index.php
    [DOCUMENT_ROOT] => 
    [REQUEST_TIME_FLOAT] => 1531091263.0059
    [REQUEST_TIME] => 1531091263

## Possible Solution
There are **different issues**
Issue 1: format the syntax to standarized Http_Query should be QUERY_STRING, also the uppercases, because the $_SERVER keys are case sensitive

issue 2:  in http get don't have the $_GET array populated, here how is solved in "nginx mode"
https://serverfault.com/questions/492860/incoming-get-array-is-empty-on-my-nginx
in php-cli is php-cgi -f index.php left=1058 right=1067 class=A language=English

issue 3: in http post: don't have the $_POST array populated, similar to issue 2

**proposals**: 
-populate REQUEST_URI with the url of the request
-add header named "function name" per example, with the function name
-populate SERVER_ADDR with the ip of the node
-populate node name and container id for logging proposals

 
## Your Environment
Docker-ce 18 and swarm
Php hello world based on itscaro templates with some adjusts

**Comment by ericstoekl** [comment]
@info2000 Thank you for your submission.

It would help a lot if you could give some example commands that led you to the conclusions that issues 1,2, and 3 exist. If there are some issues, please tell us how to reproduce them.

Do you want the Openfaas functions to return the same HTTP headers as Nginx? Or is there some standard that we should be following (in your estimation)?

The proposals are not bad but maybe give us reasons why we need these new HTTP headers?

> -populate SERVER_ADDR with the ip of the node

IP of the node for Server_Addr -- we do not necessarily want this info to be revealed to the person who calls a function.

**Comment by ericstoekl** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
@info2000 I think you could do the remapping of environmental variables from OpenFaaS Watchdog format to the (CGI) format you are referring to using a helper function. You could build this into your PHP function so that your developers don't have to see it in action. 

As for $_GET / $_POST - I'm not sure what they are meant to do. Can you link to the spec?

Alex

**Comment by alexellis** [comment]
cc @itscaro who authored the PHP template.

**Comment by jnovack** [comment]
Unsolicited third-party comments.

* Issue 1.  Apache and Nginx both include `QUERY_STRING` and `REQUEST_URI`.  Unsure about IIS.
* Issue 2/3.  I believe you have this issue because `QUERY_STRING` or `REQUEST_URI` is NOT populated by the forwarding gateway.  It is my understanding that PHP's `$_GET` is a special function/variable which populates based on the parsing of one or both of those variables.

Proposed Amendments to Proposals:

1. populate REQUEST_URI with the ~url~ URI of the request. (*URI is * `/index.html`)
2. add header named ~"function name" per example~ `X_FUNCTION_NAME`, with the function name (don't forget the `X_` for custom headers, best practice)
3. populate SERVER_ADDR with the ip of the node (*agree*)
4. populate node name and container id for logging proposals (`X_NODE_NAME` *or* `X_CONTAINER_ID`)
5. populate QUERY_STRING with the query string (everything after `?`, do not include `?`)
6. UPPERCASE all headers, for consistency (*not a standard, best practice*)

References.  Yes, these are server variables, but when they are passed as headers, you can see they are using all UPPERCASE, despite being officially case-insensitive.

1. https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond
2. https://www.nginx.com/resources/wiki/start/topics/examples/full/
3. http://php.net/manual/en/reserved.variables.server.php
4. https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by alexellis** [comment]
Thanks for the comments from everyone.

OpenFaaS functions are not involved via CGI, even though it looks similar. I am not sure this is a priority or even a goal for us right now.

My advice would be to write a very small middleware in your PHP template or function that places the variables where you like to see them taking them in from where we have them documented now.

If there is HTTP header data which is missing please list it below so we can confirm and check with the watchdog.

**Comment by alexellis** [comment]
Derek close: inactivity / lack of interest from original poster.

**Comment by jnovack** [comment]
I'm just really confused why the choice to intentionally not make something like an already established standard?

I now have to code my application to accept OpenFaaS's non-standard headers rather than just reusing my code which already used CGI standard headers.  Code that was portable between Traefik and Nginx and HAProxy now has to get rewritten to be behind an OpenFaaS. 

I do not see how this helps get the project adopted by others.

**Comment by alexellis** [comment]
@jnovack you're free to use these conventions, a very small piece of code to remap the existing established headers would get you exactly what you want. Feel free to contribute that to the upcoming PHP template. https://github.com/openfaas/templates/pull/65

OpenFaaS functions can be invoked over HTTP, but it's not the only kind of trigger so strongly binding to the PHP / CGI standard is not an immediate goal. As I said above, I'd be happy to revisit given usage / demand. 

Alex
