### ISSUE TITLE
Sample-functions: Convert ADD https:// to use curl

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#841]
## Expected Behaviour

All functions to use `curl` to get the watchdog since this can be cached by Docker.

```
RUN apk --no-cache add make curl \
    && curl -sL https://github.com/openfaas/faas/releases/download/0.9.0/fwatchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog
```

## Current Behaviour

Some use `ADD https://` which cannot be cached.

## Possible Solution

Update all samples in the faas repo and test that they still build.

**Comment by rdimitrov** [comment]
I'll be happy to cover it.

**Comment by alexellis** [comment]
Thank you. All yours.

**Comment by rdimitrov** [comment]
@alexellis Do you have any suggestions about how to handle [this](https://github.com/rdimitrov/faas/blob/eceac0a097d4df0f428f1e724c84f23b990acb76/sample-functions/BaseFunctions/golang/Dockerfile.win#L9l) Windows Dockerfile?

**Comment by rdimitrov** [comment]
* All samples for each architecture (where applicable) are updated and tested that there's no difference in terms of building. 
    * The only one left is [this one](https://github.com/rdimitrov/faas/blob/eceac0a097d4df0f428f1e724c84f23b990acb76/sample-functions/BaseFunctions/golang/Dockerfile.win#L9l)
* The changes related to each architecture are split in different commits - for ex. amd64, arm64, armhf and there's one additional for updating the docs.  

_Note: When the image is not Alpine, the RUN command is slightly changed due to the different package managers._

**Comment by alexellis** [comment]
Hi @rdimitrov I don't think anyone is using the Windows example so I'd leave it as it is for now.

**Comment by alexellis** [comment]
Do you have a pull request ready?

**Comment by alexellis** [comment]
@rdimitrov in your next PR please add the text: "Closes #...."
