### ISSUE TITLE
Gateway scale_from_zero behaviour for non-existing functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#876]
## Expected Behaviour

The gateway should not try to scale up any non-existing function deployments.

## Current Behaviour

In the deployment of OpenFaaS Cloud when I tried to access a function that didn't exist it tried to scale it to 1 and then gave a warning / error.

## Possible Solution

Dig into why this is happening, report back on the issue with some ideas for a fix. By extension add unit test coverage if missing for the function map and if possible create a failing test showing the error.

## Steps to Reproduce (for bugs)

0. Using Kubernetes
1. Deploy with `scale_from_zero` enabled
2. Visit function that doesn't exist
3. See error similar to `unable to scale function [name-here], err: error scaling HTTP code 500, http://127.0.0.1:8081/system/scale-function/name-here`

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
@rgee0 also mentioned seeing this with OpenFaaS Cloud live environment.

**Comment by rgee0** [comment]
I added a couple of tests for `cache.go` which have confirmed that the cache functions are performing as expected.

Digging deeper I think the problems lie in `external.go` because in `scaling.go` the call to `GetReplicas` does not return an error when the function isn't found. This means the execution moves on into `SetReplicas` which is where the errors that we see bubble up from.

I need to continue investigations but I think we may need to add and else here:
https://github.com/openfaas/faas/blob/af0ccc9a4506b4450e5008df4ab14eaf2714216e/gateway/plugin/external.go#L79-L84
so that if we don't get a 200 we return an error, which would see this code block exercised:
https://github.com/openfaas/faas/blob/af0ccc9a4506b4450e5008df4ab14eaf2714216e/gateway/handlers/scaling.go#L41-L49

**Comment by rgee0** [comment]
Might be a bit hacky as I've not created mock http tests previously but tests to demonstrate the failure can be found here https://github.com/openfaas/faas/compare/master...rgee0:scaleInvestigation?expand=1
`TestGetReplicasNonExistentFn` Fails as we should expect an error out of GetReplicas if the function isn't found.  Instead we see a nil error and a struct returned which consequently causes a scale event to be attempted.

**Comment by rgee0** [comment]
Derek assign: me

**Comment by alexellis** [comment]
The approach sounds good to me. Please proceed with a PR.
