### ISSUE TITLE
Add a write to logs on a scaling up event

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas#885]
## Expected Behaviour
When a scale up of a function occurs we should write some pertinent information to the log

## Current Behaviour
Only error events are logged

## Possible Solution
Look at relevant areas in `external.go` and `scaling.go` where requests and successful events could be logged.

## Steps to Reproduce (for bugs)
Not a bug

## Context
During testing of #884 it became obvious that this information would assist in aiding understanding of system behaviour in the event of a scaling event

**Comment by bartsmykla** [comment]
Derek assign: me

**Comment by bartsmykla** [comment]
@rgee0 I think that I need more info, because when I look at gateway's logs when functions are scaled I see:
```
2018/09/25 10:26:53 [Scale] function=bartsmykla-go-fn 4 => 1.
2018/09/25 10:26:53 [Scale] function=nodeinfo 1 => 4.
```
Do you mean something else than that?

**Comment by alexellis** [comment]
This is about zero to one (or to N) scaling. We already have scaling up/down messages that you can see above.

Here's the use-case - we turn on scale_from_zero on a public environment, now we want to monitor and track how well it performs. We can't do that easily since it's not in the logs. This is the line of code responsible for initiating a "wake up" or scale from zero -> https://github.com/openfaas/faas/blob/master/gateway/handlers/scaling.go#L58

Alex

**Comment by alexellis** [comment]
@bartsmykla any updates on this? I think I saw you mention this on Slack

**Comment by alexellis** [comment]
This issue has been assigned for 24 days (a month) with no progress and no updates for 17 days. I'm going to unassign it so the community can work on this.
