### ISSUE TITLE
Trying to call a function from another function.

### ISSUE THREAD

**Issue by MineMS49** [openfaas/faas#906]
I'm trying to connect two functions to one another. The goal is to reach the function B via the function A.
Functions A and B are deployed and are working as expected (on the UI at http://ip:8080/ui). They are at http://localhost:8080/function/_ .
By calling in the server http://localhost:8080/function/B with cURL it works.
By calling in the UI http://ip:8080/ui the function A it calls http://localhost:8080/function/B but return itself.
But calling B function via http://ip:8080/function/B from the UI http://ip:8080/ui of the function A it works well and the results are displayed.

## Expected Behaviour

Calling B function through A function using the localhost link should be possible and would return the B function response and the A function response.

## Current Behaviour

Calling B function through A function using the localhost link return the A function response two times.

**Situation**
The server is running on Ubuntu 16.04
Functions are based on the Python3 sample and are programmed in Python 3.4

**Comment by alexellis** [comment]
Please checkout the documentation site and the workshop. https://github.com/openfaas/workshop/blob/master/lab4.md#create-workflows

**Comment by martindekov** [comment]
Hello @MineMS49 this is little confusing at first but in general better use the gateway `https://gateway:8080/function/..` to call one function from another rather than `localhost` or the external IP. More information could be found in [workshop lab4](https://github.com/openfaas/workshop/blob/f27ff19c87b0933c51799586d83d5e75cbd78eb2/lab4.md) we invoke one function from another there.
