### ISSUE TITLE
Change base image of function

### ISSUE THREAD

**Issue by vijaysng** [openfaas/faas#910]
I am trying to create multiple functions in python. Size of image of each function is approximately 526MB.
Is there a way to change the base image of the image created. So that the size of the final image can be reduced ?

**Comment by Templum** [comment]
@vijaysng are your functions are based on the official template? It is generally possible to create an own base image and if you use alpine as a base you might be able to reduce the overall size.

Another thing to highlight is that docker reuses layer. And if all images extend the same base image. It will only download the base image once and not multiple time

**Comment by alexellis** [comment]
Hi @vijaysng I'm not sure where or how you're seeing this? For one thing I'd like to ask you to fill out the whole issue template instead of deleting it. It *helps us, help you*.

I just used the official python3 template (which is based upon Alpine Linux) and it came out with the following:

```
faas-cli new --lang python3 sample1
faas-cli build -f sample1.yml
docker images |grep sample1

sample1                           latest              38967106d9cd        5 seconds ago       82.8MB
```

I'll close this issue since we have no useful information from you and to Simon's point - images are 1) layered (so you only ship deltas) and 2) you need to fill out the whole template.

Feel free to keep commenting.

**Comment by alexellis** [comment]
Issue template https://github.com/openfaas/faas/blob/master/.github/ISSUE_TEMPLATE.md
