### ISSUE TITLE
Question: no response using Node.js & MongoDB / Redis?

### ISSUE THREAD

**Issue by feichao** [openfaas/faas#942]
# return 502 when invoke a function that uses MongoDB or Redis

## Expected Behaviour
the function should return 200 

## Current Behaviour
1. the function returns 502
2. ### but the data has been inserted into Redis

## Possible Solution
none

## Steps to Reproduce (for bugs)
1. deploy openfaas according to "https://medium.com/devopslinks/getting-started-with-openfaas-on-minikube-634502c7acdf"
2. install redis: helm install stable/redis --name openfaas-redis --namespace openfaas-fn --set usePassword=false
3. insert data into Redis in my function when invoked
`
const redis = RedisClient(6379, process.env.redis);
redis.set('mytime', +new Date)
`
4. 
![502](https://user-images.githubusercontent.com/11988943/47831527-e2ebbd80-ddcb-11e8-8925-159808878f43.jpg)

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ):  0.7.6

* Docker version `docker version` (e.g. Docker 17.0.05 ):  Version: 17.12.1-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?: Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

**Comment by feichao** [comment]
this is my function:

`const RedisClient = require("redis").createClient;

module.exports = (body, callback) => {
    const redis = RedisClient(6379, process.env.redis);
    redis.set('mytime', +new Date)
    callback(null, { status: 'insert done' })
}
`

**Comment by alexellis** [comment]
Hi @feichao, thanks for your interest in OpenFaaS.

When using the standard Node.js template you will need to close the Redis or Mongo connection/client before the callback will return, this is because they both block the thread.

If you'd like to avoid this then use the [node8-express template](https://github.com/openfaas-incubator/node8-express-template) which can maintain a DB connection pool or open Redis client between requests. 

https://blog.alexellis.io/serverless-databases-with-openfaas-and-mongo/

Please feel free to join slack by emailing alex@openfaas.com for your invite. 

Regards,

Alex

**Comment by alexellis** [comment]
Here's a fully working example tested on Kubernetes: https://gist.github.com/alexellis/e05a7b573ae22b209f0214d5766ff07e

Let me know how you get on. I'll close this support issue but feel free to keep asking questions etc.

Alex

**Comment by alexellis** [comment]
Derek add label: support

**Comment by alexellis** [comment]
Derek close
