### ISSUE TITLE
Proposal: return not found errors from async route handler

### ISSUE THREAD

**Issue by khenam** [openfaas/faas#947]
Gateway don't verify if function exists or is ready to accept async request.

## Expected Behaviour

if function do not exist, expected receive code 400 or 500
if function is not ready, expected receive code 400 or 500

## Current Behaviour

if function do not exist, receive code 202
if function is not ready, receive code 202

## Possible Solution

check function state before put in NATS

## Steps to Reproduce (for bugs)

1. echo -n "LaterIsBetter" | faas-cli invoke figlet2 --async --header "X-Callback-Url=http://requestbin.fullcontact.com/14by9pq1"
2. receive message "Function submitted asynchronously."

## Context

I try create a sequence of call but if something goes wrong, this change will help is some point in call stack can't run.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  70ebebb71f015f4edb0c3e1f03ef3d262b1d84f6
 version: 0.7.7

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by LucasRoesler** [comment]
Changing the system to deny asynchronous requests of the function is not ready can lead to data loss because there is no way to ensure that the client will or even can retry the original request. 

To avoid data loss, it is normal to always accept the messages into the queue. Then, via monitoring metrics and alerting the developers that the queue is being processed correctly. 

this page from nats has an interesting discussion on this https://nats.io/documentation/server/gnatsd-slow-consumers/

It is important to note that we use nats-streaming and that it does provide a metrics endpoint that you can use to gather the needed metrics. 

Instead of rejecting request data and responding with an error I think we should  consider adding https://github.com/nats-io/prometheus-nats-exporter to the stack so that we can improve the monitoring and alerting about the asynchronous queues

**Comment by khenam** [comment]
I agree, thanks.
But in case of the function don't exist? Is it make sense?

**Comment by LucasRoesler** [comment]
Conceptually it makes sense, but it is hard to know if a function doesn't exist because a hard replace (delete and deploy) is occurring or is it because the function really doesn't exist

**Comment by khenam** [comment]
Maybe setting retry and retry-interval helps?

**Comment by LucasRoesler** [comment]
I am not sure I completely understand where we would put the retry, could you sketch out the idea a little more?

**Comment by khenam** [comment]
sorry for taking time to respond
@alexellis I am studying a way to write a code that is practically focused on faas and is still performatic, but I am checking for the points of failure that could be a problem for asynchronous calls. one of our ideas is to adapt gRPC to work with openfaas.
@LucasRoesler The idea is to allow NATS handlers to retry the limit of times it is set up via the http header and if it needs a break between attempts it respects that as well.
I'm going to draw this sketch it and put it here later.

**Comment by alexellis** [comment]
@khenam retries would be done or handled in the [nats-queue-worker](https://github.com/openfaas/nats-queue-worker) rather than here at the ingestion point.

I think at this point we should close this issue and mark it #revisit - this just means the suggestion won't be worked on as suggested right now, but we can continue to keep the discussion going and find out more about your use-case.

**Comment by alexellis** [comment]
Derek add label: revisit

**Comment by alexellis** [comment]
Derek close
