### ISSUE TITLE
Proposal: Notify when async function finish

### ISSUE THREAD

**Issue by tal181** [openfaas/faas#983]
It will be nice if we will be able to monitor the state of a function running/success/failed

## Current Behaviour
No way to know the function status

## Possible Solution
When async function is triggered, create an Id and return to the user.
Expose an api to query the state of the function using the id.

**Comment by alexellis** [comment]
Hi @tal181,

Thanks for using OpenFaaS.

I've got some good news for you, everything you've asked for is already supported. I'll give you some details and close the issue. Feel free to join Slack to ask for more help.


Alex

**Comment by alexellis** [comment]
> It will be nice if we will be able to monitor the state of a function running/success/failed

You can monitor the invocations using the built-in Prometheus metrics these will give you the HTTP code which represents the success/failure.

When invoking an async function you can specify a callback URL so that the system will invoke that endpoint upon completion. It will also pass back a request-id that you got when you sent the initial request.

Documentation:

https://docs.openfaas.com/deployment/troubleshooting/#asynchronous-functions

Self-paced learning:

https://github.com/openfaas/workshop/blob/master/lab7.md

Alex

**Comment by alexellis** [comment]
@ivanayov please can we add a note on `X-Call-Id` to the docs and troubleshooting guide?

**Comment by tal181** [comment]
Hi Alex,
Thank you for your response.
Can I somehow monitor the function progress(running/completed) with
the X-Call-Id
?
Thanks,
Tal

**Comment by ivanayov** [comment]
Hi @tal181 ,

Yes, you can. If you put `X-Callback-Url` header, once the async-function finishes, it will send the response there, containing the `X-Call-Id`. If you set the `X-Call-Id` header on invocation, then you can compare the values. This is insecure if you don't use `https`.

There may have better approaches as well, but this is what comes to mind as a solution.

Ivana
